// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sf/headinfo/v1/headinfo.proto

package pbheadinfoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/streamingfast/pbgo/sf/headinfo/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HeadInfoName is the fully-qualified name of the HeadInfo service.
	HeadInfoName = "sf.headinfo.v1.HeadInfo"
	// StreamingHeadInfoName is the fully-qualified name of the StreamingHeadInfo service.
	StreamingHeadInfoName = "sf.headinfo.v1.StreamingHeadInfo"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HeadInfoGetHeadInfoProcedure is the fully-qualified name of the HeadInfo's GetHeadInfo RPC.
	HeadInfoGetHeadInfoProcedure = "/sf.headinfo.v1.HeadInfo/GetHeadInfo"
	// StreamingHeadInfoStreamHeadInfoProcedure is the fully-qualified name of the StreamingHeadInfo's
	// StreamHeadInfo RPC.
	StreamingHeadInfoStreamHeadInfoProcedure = "/sf.headinfo.v1.StreamingHeadInfo/StreamHeadInfo"
)

// HeadInfoClient is a client for the sf.headinfo.v1.HeadInfo service.
type HeadInfoClient interface {
	GetHeadInfo(context.Context, *connect.Request[v1.HeadInfoRequest]) (*connect.Response[v1.HeadInfoResponse], error)
}

// NewHeadInfoClient constructs a client for the sf.headinfo.v1.HeadInfo service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHeadInfoClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HeadInfoClient {
	baseURL = strings.TrimRight(baseURL, "/")
	headInfoMethods := v1.File_sf_headinfo_v1_headinfo_proto.Services().ByName("HeadInfo").Methods()
	return &headInfoClient{
		getHeadInfo: connect.NewClient[v1.HeadInfoRequest, v1.HeadInfoResponse](
			httpClient,
			baseURL+HeadInfoGetHeadInfoProcedure,
			connect.WithSchema(headInfoMethods.ByName("GetHeadInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// headInfoClient implements HeadInfoClient.
type headInfoClient struct {
	getHeadInfo *connect.Client[v1.HeadInfoRequest, v1.HeadInfoResponse]
}

// GetHeadInfo calls sf.headinfo.v1.HeadInfo.GetHeadInfo.
func (c *headInfoClient) GetHeadInfo(ctx context.Context, req *connect.Request[v1.HeadInfoRequest]) (*connect.Response[v1.HeadInfoResponse], error) {
	return c.getHeadInfo.CallUnary(ctx, req)
}

// HeadInfoHandler is an implementation of the sf.headinfo.v1.HeadInfo service.
type HeadInfoHandler interface {
	GetHeadInfo(context.Context, *connect.Request[v1.HeadInfoRequest]) (*connect.Response[v1.HeadInfoResponse], error)
}

// NewHeadInfoHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHeadInfoHandler(svc HeadInfoHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	headInfoMethods := v1.File_sf_headinfo_v1_headinfo_proto.Services().ByName("HeadInfo").Methods()
	headInfoGetHeadInfoHandler := connect.NewUnaryHandler(
		HeadInfoGetHeadInfoProcedure,
		svc.GetHeadInfo,
		connect.WithSchema(headInfoMethods.ByName("GetHeadInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sf.headinfo.v1.HeadInfo/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HeadInfoGetHeadInfoProcedure:
			headInfoGetHeadInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHeadInfoHandler returns CodeUnimplemented from all methods.
type UnimplementedHeadInfoHandler struct{}

func (UnimplementedHeadInfoHandler) GetHeadInfo(context.Context, *connect.Request[v1.HeadInfoRequest]) (*connect.Response[v1.HeadInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sf.headinfo.v1.HeadInfo.GetHeadInfo is not implemented"))
}

// StreamingHeadInfoClient is a client for the sf.headinfo.v1.StreamingHeadInfo service.
type StreamingHeadInfoClient interface {
	StreamHeadInfo(context.Context, *connect.Request[v1.HeadInfoRequest]) (*connect.ServerStreamForClient[v1.HeadInfoResponse], error)
}

// NewStreamingHeadInfoClient constructs a client for the sf.headinfo.v1.StreamingHeadInfo service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStreamingHeadInfoClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StreamingHeadInfoClient {
	baseURL = strings.TrimRight(baseURL, "/")
	streamingHeadInfoMethods := v1.File_sf_headinfo_v1_headinfo_proto.Services().ByName("StreamingHeadInfo").Methods()
	return &streamingHeadInfoClient{
		streamHeadInfo: connect.NewClient[v1.HeadInfoRequest, v1.HeadInfoResponse](
			httpClient,
			baseURL+StreamingHeadInfoStreamHeadInfoProcedure,
			connect.WithSchema(streamingHeadInfoMethods.ByName("StreamHeadInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// streamingHeadInfoClient implements StreamingHeadInfoClient.
type streamingHeadInfoClient struct {
	streamHeadInfo *connect.Client[v1.HeadInfoRequest, v1.HeadInfoResponse]
}

// StreamHeadInfo calls sf.headinfo.v1.StreamingHeadInfo.StreamHeadInfo.
func (c *streamingHeadInfoClient) StreamHeadInfo(ctx context.Context, req *connect.Request[v1.HeadInfoRequest]) (*connect.ServerStreamForClient[v1.HeadInfoResponse], error) {
	return c.streamHeadInfo.CallServerStream(ctx, req)
}

// StreamingHeadInfoHandler is an implementation of the sf.headinfo.v1.StreamingHeadInfo service.
type StreamingHeadInfoHandler interface {
	StreamHeadInfo(context.Context, *connect.Request[v1.HeadInfoRequest], *connect.ServerStream[v1.HeadInfoResponse]) error
}

// NewStreamingHeadInfoHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStreamingHeadInfoHandler(svc StreamingHeadInfoHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	streamingHeadInfoMethods := v1.File_sf_headinfo_v1_headinfo_proto.Services().ByName("StreamingHeadInfo").Methods()
	streamingHeadInfoStreamHeadInfoHandler := connect.NewServerStreamHandler(
		StreamingHeadInfoStreamHeadInfoProcedure,
		svc.StreamHeadInfo,
		connect.WithSchema(streamingHeadInfoMethods.ByName("StreamHeadInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sf.headinfo.v1.StreamingHeadInfo/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StreamingHeadInfoStreamHeadInfoProcedure:
			streamingHeadInfoStreamHeadInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStreamingHeadInfoHandler returns CodeUnimplemented from all methods.
type UnimplementedStreamingHeadInfoHandler struct{}

func (UnimplementedStreamingHeadInfoHandler) StreamHeadInfo(context.Context, *connect.Request[v1.HeadInfoRequest], *connect.ServerStream[v1.HeadInfoResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sf.headinfo.v1.StreamingHeadInfo.StreamHeadInfo is not implemented"))
}
