// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: sf/search/v1/search.proto

package pbsearch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Backend_StreamMatches_FullMethodName = "/sf.search.v1.Backend/StreamMatches"
)

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendClient interface {
	StreamMatches(ctx context.Context, in *BackendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchMatch], error)
}

type backendClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendClient(cc grpc.ClientConnInterface) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) StreamMatches(ctx context.Context, in *BackendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchMatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Backend_ServiceDesc.Streams[0], Backend_StreamMatches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackendRequest, SearchMatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Backend_StreamMatchesClient = grpc.ServerStreamingClient[SearchMatch]

// BackendServer is the server API for Backend service.
// All implementations should embed UnimplementedBackendServer
// for forward compatibility.
type BackendServer interface {
	StreamMatches(*BackendRequest, grpc.ServerStreamingServer[SearchMatch]) error
}

// UnimplementedBackendServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendServer struct{}

func (UnimplementedBackendServer) StreamMatches(*BackendRequest, grpc.ServerStreamingServer[SearchMatch]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMatches not implemented")
}
func (UnimplementedBackendServer) testEmbeddedByValue() {}

// UnsafeBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServer will
// result in compilation errors.
type UnsafeBackendServer interface {
	mustEmbedUnimplementedBackendServer()
}

func RegisterBackendServer(s grpc.ServiceRegistrar, srv BackendServer) {
	// If the following call pancis, it indicates UnimplementedBackendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Backend_ServiceDesc, srv)
}

func _Backend_StreamMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BackendRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackendServer).StreamMatches(m, &grpc.GenericServerStream[BackendRequest, SearchMatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Backend_StreamMatchesServer = grpc.ServerStreamingServer[SearchMatch]

// Backend_ServiceDesc is the grpc.ServiceDesc for Backend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.search.v1.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMatches",
			Handler:       _Backend_StreamMatches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sf/search/v1/search.proto",
}

const (
	Router_StreamMatches_FullMethodName = "/sf.search.v1.Router/StreamMatches"
)

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterClient interface {
	StreamMatches(ctx context.Context, in *RouterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchMatch], error)
}

type routerClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterClient(cc grpc.ClientConnInterface) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) StreamMatches(ctx context.Context, in *RouterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchMatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Router_ServiceDesc.Streams[0], Router_StreamMatches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RouterRequest, SearchMatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Router_StreamMatchesClient = grpc.ServerStreamingClient[SearchMatch]

// RouterServer is the server API for Router service.
// All implementations should embed UnimplementedRouterServer
// for forward compatibility.
type RouterServer interface {
	StreamMatches(*RouterRequest, grpc.ServerStreamingServer[SearchMatch]) error
}

// UnimplementedRouterServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterServer struct{}

func (UnimplementedRouterServer) StreamMatches(*RouterRequest, grpc.ServerStreamingServer[SearchMatch]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMatches not implemented")
}
func (UnimplementedRouterServer) testEmbeddedByValue() {}

// UnsafeRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServer will
// result in compilation errors.
type UnsafeRouterServer interface {
	mustEmbedUnimplementedRouterServer()
}

func RegisterRouterServer(s grpc.ServiceRegistrar, srv RouterServer) {
	// If the following call pancis, it indicates UnimplementedRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Router_ServiceDesc, srv)
}

func _Router_StreamMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RouterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouterServer).StreamMatches(m, &grpc.GenericServerStream[RouterRequest, SearchMatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Router_StreamMatchesServer = grpc.ServerStreamingServer[SearchMatch]

// Router_ServiceDesc is the grpc.ServiceDesc for Router service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Router_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.search.v1.Router",
	HandlerType: (*RouterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMatches",
			Handler:       _Router_StreamMatches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sf/search/v1/search.proto",
}

const (
	ForkResolver_StreamUndoMatches_FullMethodName = "/sf.search.v1.ForkResolver/StreamUndoMatches"
)

// ForkResolverClient is the client API for ForkResolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForkResolverClient interface {
	StreamUndoMatches(ctx context.Context, in *ForkResolveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchMatch], error)
}

type forkResolverClient struct {
	cc grpc.ClientConnInterface
}

func NewForkResolverClient(cc grpc.ClientConnInterface) ForkResolverClient {
	return &forkResolverClient{cc}
}

func (c *forkResolverClient) StreamUndoMatches(ctx context.Context, in *ForkResolveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchMatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ForkResolver_ServiceDesc.Streams[0], ForkResolver_StreamUndoMatches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForkResolveRequest, SearchMatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForkResolver_StreamUndoMatchesClient = grpc.ServerStreamingClient[SearchMatch]

// ForkResolverServer is the server API for ForkResolver service.
// All implementations should embed UnimplementedForkResolverServer
// for forward compatibility.
type ForkResolverServer interface {
	StreamUndoMatches(*ForkResolveRequest, grpc.ServerStreamingServer[SearchMatch]) error
}

// UnimplementedForkResolverServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForkResolverServer struct{}

func (UnimplementedForkResolverServer) StreamUndoMatches(*ForkResolveRequest, grpc.ServerStreamingServer[SearchMatch]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUndoMatches not implemented")
}
func (UnimplementedForkResolverServer) testEmbeddedByValue() {}

// UnsafeForkResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForkResolverServer will
// result in compilation errors.
type UnsafeForkResolverServer interface {
	mustEmbedUnimplementedForkResolverServer()
}

func RegisterForkResolverServer(s grpc.ServiceRegistrar, srv ForkResolverServer) {
	// If the following call pancis, it indicates UnimplementedForkResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForkResolver_ServiceDesc, srv)
}

func _ForkResolver_StreamUndoMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ForkResolveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ForkResolverServer).StreamUndoMatches(m, &grpc.GenericServerStream[ForkResolveRequest, SearchMatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForkResolver_StreamUndoMatchesServer = grpc.ServerStreamingServer[SearchMatch]

// ForkResolver_ServiceDesc is the grpc.ServiceDesc for ForkResolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForkResolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.search.v1.ForkResolver",
	HandlerType: (*ForkResolverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUndoMatches",
			Handler:       _ForkResolver_StreamUndoMatches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sf/search/v1/search.proto",
}
