// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sf/search/v1/search.proto

package pbsearch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouterRequest_Mode int32

const (
	RouterRequest_STREAMING RouterRequest_Mode = 0
	RouterRequest_PAGINATED RouterRequest_Mode = 1
)

// Enum value maps for RouterRequest_Mode.
var (
	RouterRequest_Mode_name = map[int32]string{
		0: "STREAMING",
		1: "PAGINATED",
	}
	RouterRequest_Mode_value = map[string]int32{
		"STREAMING": 0,
		"PAGINATED": 1,
	}
)

func (x RouterRequest_Mode) Enum() *RouterRequest_Mode {
	p := new(RouterRequest_Mode)
	*p = x
	return p
}

func (x RouterRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouterRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_search_v1_search_proto_enumTypes[0].Descriptor()
}

func (RouterRequest_Mode) Type() protoreflect.EnumType {
	return &file_sf_search_v1_search_proto_enumTypes[0]
}

func (x RouterRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouterRequest_Mode.Descriptor instead.
func (RouterRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_sf_search_v1_search_proto_rawDescGZIP(), []int{3, 0}
}

type ForkResolveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ForkedBlockRefs []*BlockRef            `protobuf:"bytes,2,rep,name=forkedBlockRefs,proto3" json:"forkedBlockRefs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForkResolveRequest) Reset() {
	*x = ForkResolveRequest{}
	mi := &file_sf_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkResolveRequest) ProtoMessage() {}

func (x *ForkResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkResolveRequest.ProtoReflect.Descriptor instead.
func (*ForkResolveRequest) Descriptor() ([]byte, []int) {
	return file_sf_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *ForkResolveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ForkResolveRequest) GetForkedBlockRefs() []*BlockRef {
	if x != nil {
		return x.ForkedBlockRefs
	}
	return nil
}

type BlockRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      uint64                 `protobuf:"varint,1,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	BlockID       string                 `protobuf:"bytes,2,opt,name=blockID,proto3" json:"blockID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRef) Reset() {
	*x = BlockRef{}
	mi := &file_sf_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRef) ProtoMessage() {}

func (x *BlockRef) ProtoReflect() protoreflect.Message {
	mi := &file_sf_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRef.ProtoReflect.Descriptor instead.
func (*BlockRef) Descriptor() ([]byte, []int) {
	return file_sf_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *BlockRef) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *BlockRef) GetBlockID() string {
	if x != nil {
		return x.BlockID
	}
	return ""
}

type BackendRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Query        string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	LowBlockNum  uint64                 `protobuf:"varint,2,opt,name=lowBlockNum,proto3" json:"lowBlockNum,omitempty"`   // Inclusive
	HighBlockNum uint64                 `protobuf:"varint,3,opt,name=highBlockNum,proto3" json:"highBlockNum,omitempty"` // Inclusive
	Descending   bool                   `protobuf:"varint,4,opt,name=descending,proto3" json:"descending,omitempty"`
	// More specific to the live / reversible backend
	WithReversible       bool   `protobuf:"varint,5,opt,name=withReversible,proto3" json:"withReversible,omitempty"`         // Fails on Archive
	LiveMarkerInterval   uint64 `protobuf:"varint,6,opt,name=liveMarkerInterval,proto3" json:"liveMarkerInterval,omitempty"` // in blocks
	StopAtVirtualHead    bool   `protobuf:"varint,7,opt,name=stopAtVirtualHead,proto3" json:"stopAtVirtualHead,omitempty"`
	NavigateFromBlockID  string `protobuf:"bytes,8,opt,name=navigateFromBlockID,proto3" json:"navigateFromBlockID,omitempty"`    // When a cursor was provided, which had a HEAD block ID
	NavigateFromBlockNum uint64 `protobuf:"varint,9,opt,name=navigateFromBlockNum,proto3" json:"navigateFromBlockNum,omitempty"` // When a cursor was provided, which had a HEAD block ID
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BackendRequest) Reset() {
	*x = BackendRequest{}
	mi := &file_sf_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendRequest) ProtoMessage() {}

func (x *BackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendRequest.ProtoReflect.Descriptor instead.
func (*BackendRequest) Descriptor() ([]byte, []int) {
	return file_sf_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *BackendRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *BackendRequest) GetLowBlockNum() uint64 {
	if x != nil {
		return x.LowBlockNum
	}
	return 0
}

func (x *BackendRequest) GetHighBlockNum() uint64 {
	if x != nil {
		return x.HighBlockNum
	}
	return 0
}

func (x *BackendRequest) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

func (x *BackendRequest) GetWithReversible() bool {
	if x != nil {
		return x.WithReversible
	}
	return false
}

func (x *BackendRequest) GetLiveMarkerInterval() uint64 {
	if x != nil {
		return x.LiveMarkerInterval
	}
	return 0
}

func (x *BackendRequest) GetStopAtVirtualHead() bool {
	if x != nil {
		return x.StopAtVirtualHead
	}
	return false
}

func (x *BackendRequest) GetNavigateFromBlockID() string {
	if x != nil {
		return x.NavigateFromBlockID
	}
	return ""
}

func (x *BackendRequest) GetNavigateFromBlockNum() uint64 {
	if x != nil {
		return x.NavigateFromBlockNum
	}
	return 0
}

type RouterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Query              string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	LowBlockNum        int64                  `protobuf:"varint,2,opt,name=lowBlockNum,proto3" json:"lowBlockNum,omitempty"`   // Inclusive
	HighBlockNum       int64                  `protobuf:"varint,3,opt,name=highBlockNum,proto3" json:"highBlockNum,omitempty"` // Inclusive
	LowBlockUnbounded  bool                   `protobuf:"varint,13,opt,name=lowBlockUnbounded,proto3" json:"lowBlockUnbounded,omitempty"`
	HighBlockUnbounded bool                   `protobuf:"varint,14,opt,name=highBlockUnbounded,proto3" json:"highBlockUnbounded,omitempty"`
	Descending         bool                   `protobuf:"varint,4,opt,name=descending,proto3" json:"descending,omitempty"`
	Cursor             string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit              int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	WithReversible     bool                   `protobuf:"varint,7,opt,name=withReversible,proto3" json:"withReversible,omitempty"` // Fails on Archive
	Mode               RouterRequest_Mode     `protobuf:"varint,8,opt,name=mode,proto3,enum=sf.search.v1.RouterRequest_Mode" json:"mode,omitempty"`
	// Legacy boundaries, overrides `lowBlockNum` and `highBlockNum`.
	UseLegacyBoundaries bool   `protobuf:"varint,9,opt,name=useLegacyBoundaries,proto3" json:"useLegacyBoundaries,omitempty"`
	StartBlock          uint64 `protobuf:"varint,10,opt,name=startBlock,proto3" json:"startBlock,omitempty"`
	BlockCount          uint64 `protobuf:"varint,11,opt,name=blockCount,proto3" json:"blockCount,omitempty"`
	LiveMarkerInterval  uint64 `protobuf:"varint,12,opt,name=liveMarkerInterval,proto3" json:"liveMarkerInterval,omitempty"` // in blocks
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RouterRequest) Reset() {
	*x = RouterRequest{}
	mi := &file_sf_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterRequest) ProtoMessage() {}

func (x *RouterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterRequest.ProtoReflect.Descriptor instead.
func (*RouterRequest) Descriptor() ([]byte, []int) {
	return file_sf_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *RouterRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RouterRequest) GetLowBlockNum() int64 {
	if x != nil {
		return x.LowBlockNum
	}
	return 0
}

func (x *RouterRequest) GetHighBlockNum() int64 {
	if x != nil {
		return x.HighBlockNum
	}
	return 0
}

func (x *RouterRequest) GetLowBlockUnbounded() bool {
	if x != nil {
		return x.LowBlockUnbounded
	}
	return false
}

func (x *RouterRequest) GetHighBlockUnbounded() bool {
	if x != nil {
		return x.HighBlockUnbounded
	}
	return false
}

func (x *RouterRequest) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

func (x *RouterRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *RouterRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RouterRequest) GetWithReversible() bool {
	if x != nil {
		return x.WithReversible
	}
	return false
}

func (x *RouterRequest) GetMode() RouterRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return RouterRequest_STREAMING
}

func (x *RouterRequest) GetUseLegacyBoundaries() bool {
	if x != nil {
		return x.UseLegacyBoundaries
	}
	return false
}

func (x *RouterRequest) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *RouterRequest) GetBlockCount() uint64 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *RouterRequest) GetLiveMarkerInterval() uint64 {
	if x != nil {
		return x.LiveMarkerInterval
	}
	return 0
}

type SearchMatch struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TrxIdPrefix string                 `protobuf:"bytes,1,opt,name=trxIdPrefix,proto3" json:"trxIdPrefix,omitempty"`
	BlockNum    uint64                 `protobuf:"varint,2,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	Index       uint64                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Cursor      string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Holds chain specific Protobuf message, this usually contains informations about how the
	// document are indexed (for example at the action level on EOSIO). Check out chain specific
	// repository for exact possible message.
	ChainSpecific *anypb.Any `protobuf:"bytes,13,opt,name=chainSpecific,proto3" json:"chainSpecific,omitempty"`
	Undo          bool       `protobuf:"varint,25,opt,name=undo,proto3" json:"undo,omitempty"`
	IrrBlockNum   uint64     `protobuf:"varint,26,opt,name=irrBlockNum,proto3" json:"irrBlockNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMatch) Reset() {
	*x = SearchMatch{}
	mi := &file_sf_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMatch) ProtoMessage() {}

func (x *SearchMatch) ProtoReflect() protoreflect.Message {
	mi := &file_sf_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMatch.ProtoReflect.Descriptor instead.
func (*SearchMatch) Descriptor() ([]byte, []int) {
	return file_sf_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchMatch) GetTrxIdPrefix() string {
	if x != nil {
		return x.TrxIdPrefix
	}
	return ""
}

func (x *SearchMatch) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *SearchMatch) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SearchMatch) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SearchMatch) GetChainSpecific() *anypb.Any {
	if x != nil {
		return x.ChainSpecific
	}
	return nil
}

func (x *SearchMatch) GetUndo() bool {
	if x != nil {
		return x.Undo
	}
	return false
}

func (x *SearchMatch) GetIrrBlockNum() uint64 {
	if x != nil {
		return x.IrrBlockNum
	}
	return 0
}

var File_sf_search_v1_search_proto protoreflect.FileDescriptor

const file_sf_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x19sf/search/v1/search.proto\x12\fsf.search.v1\x1a\x19google/protobuf/any.proto\"l\n" +
	"\x12ForkResolveRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12@\n" +
	"\x0fforkedBlockRefs\x18\x02 \x03(\v2\x16.sf.search.v1.BlockRefR\x0fforkedBlockRefs\"@\n" +
	"\bBlockRef\x12\x1a\n" +
	"\bblockNum\x18\x01 \x01(\x04R\bblockNum\x12\x18\n" +
	"\ablockID\x18\x02 \x01(\tR\ablockID\"\xf8\x02\n" +
	"\x0eBackendRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12 \n" +
	"\vlowBlockNum\x18\x02 \x01(\x04R\vlowBlockNum\x12\"\n" +
	"\fhighBlockNum\x18\x03 \x01(\x04R\fhighBlockNum\x12\x1e\n" +
	"\n" +
	"descending\x18\x04 \x01(\bR\n" +
	"descending\x12&\n" +
	"\x0ewithReversible\x18\x05 \x01(\bR\x0ewithReversible\x12.\n" +
	"\x12liveMarkerInterval\x18\x06 \x01(\x04R\x12liveMarkerInterval\x12,\n" +
	"\x11stopAtVirtualHead\x18\a \x01(\bR\x11stopAtVirtualHead\x120\n" +
	"\x13navigateFromBlockID\x18\b \x01(\tR\x13navigateFromBlockID\x122\n" +
	"\x14navigateFromBlockNum\x18\t \x01(\x04R\x14navigateFromBlockNum\"\xbd\x04\n" +
	"\rRouterRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12 \n" +
	"\vlowBlockNum\x18\x02 \x01(\x03R\vlowBlockNum\x12\"\n" +
	"\fhighBlockNum\x18\x03 \x01(\x03R\fhighBlockNum\x12,\n" +
	"\x11lowBlockUnbounded\x18\r \x01(\bR\x11lowBlockUnbounded\x12.\n" +
	"\x12highBlockUnbounded\x18\x0e \x01(\bR\x12highBlockUnbounded\x12\x1e\n" +
	"\n" +
	"descending\x18\x04 \x01(\bR\n" +
	"descending\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\x12&\n" +
	"\x0ewithReversible\x18\a \x01(\bR\x0ewithReversible\x124\n" +
	"\x04mode\x18\b \x01(\x0e2 .sf.search.v1.RouterRequest.ModeR\x04mode\x120\n" +
	"\x13useLegacyBoundaries\x18\t \x01(\bR\x13useLegacyBoundaries\x12\x1e\n" +
	"\n" +
	"startBlock\x18\n" +
	" \x01(\x04R\n" +
	"startBlock\x12\x1e\n" +
	"\n" +
	"blockCount\x18\v \x01(\x04R\n" +
	"blockCount\x12.\n" +
	"\x12liveMarkerInterval\x18\f \x01(\x04R\x12liveMarkerInterval\"$\n" +
	"\x04Mode\x12\r\n" +
	"\tSTREAMING\x10\x00\x12\r\n" +
	"\tPAGINATED\x10\x01\"\xf7\x01\n" +
	"\vSearchMatch\x12 \n" +
	"\vtrxIdPrefix\x18\x01 \x01(\tR\vtrxIdPrefix\x12\x1a\n" +
	"\bblockNum\x18\x02 \x01(\x04R\bblockNum\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x04R\x05index\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12:\n" +
	"\rchainSpecific\x18\r \x01(\v2\x14.google.protobuf.AnyR\rchainSpecific\x12\x12\n" +
	"\x04undo\x18\x19 \x01(\bR\x04undo\x12 \n" +
	"\virrBlockNum\x18\x1a \x01(\x04R\virrBlockNumJ\x04\b\n" +
	"\x10\fJ\x04\b\x0e\x10\x192U\n" +
	"\aBackend\x12J\n" +
	"\rStreamMatches\x12\x1c.sf.search.v1.BackendRequest\x1a\x19.sf.search.v1.SearchMatch0\x012S\n" +
	"\x06Router\x12I\n" +
	"\rStreamMatches\x12\x1b.sf.search.v1.RouterRequest\x1a\x19.sf.search.v1.SearchMatch0\x012b\n" +
	"\fForkResolver\x12R\n" +
	"\x11StreamUndoMatches\x12 .sf.search.v1.ForkResolveRequest\x1a\x19.sf.search.v1.SearchMatch0\x01B5Z3github.com/streamingfast/pbgo/sf/search/v1;pbsearchb\x06proto3"

var (
	file_sf_search_v1_search_proto_rawDescOnce sync.Once
	file_sf_search_v1_search_proto_rawDescData []byte
)

func file_sf_search_v1_search_proto_rawDescGZIP() []byte {
	file_sf_search_v1_search_proto_rawDescOnce.Do(func() {
		file_sf_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_search_v1_search_proto_rawDesc), len(file_sf_search_v1_search_proto_rawDesc)))
	})
	return file_sf_search_v1_search_proto_rawDescData
}

var file_sf_search_v1_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sf_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sf_search_v1_search_proto_goTypes = []any{
	(RouterRequest_Mode)(0),    // 0: sf.search.v1.RouterRequest.Mode
	(*ForkResolveRequest)(nil), // 1: sf.search.v1.ForkResolveRequest
	(*BlockRef)(nil),           // 2: sf.search.v1.BlockRef
	(*BackendRequest)(nil),     // 3: sf.search.v1.BackendRequest
	(*RouterRequest)(nil),      // 4: sf.search.v1.RouterRequest
	(*SearchMatch)(nil),        // 5: sf.search.v1.SearchMatch
	(*anypb.Any)(nil),          // 6: google.protobuf.Any
}
var file_sf_search_v1_search_proto_depIdxs = []int32{
	2, // 0: sf.search.v1.ForkResolveRequest.forkedBlockRefs:type_name -> sf.search.v1.BlockRef
	0, // 1: sf.search.v1.RouterRequest.mode:type_name -> sf.search.v1.RouterRequest.Mode
	6, // 2: sf.search.v1.SearchMatch.chainSpecific:type_name -> google.protobuf.Any
	3, // 3: sf.search.v1.Backend.StreamMatches:input_type -> sf.search.v1.BackendRequest
	4, // 4: sf.search.v1.Router.StreamMatches:input_type -> sf.search.v1.RouterRequest
	1, // 5: sf.search.v1.ForkResolver.StreamUndoMatches:input_type -> sf.search.v1.ForkResolveRequest
	5, // 6: sf.search.v1.Backend.StreamMatches:output_type -> sf.search.v1.SearchMatch
	5, // 7: sf.search.v1.Router.StreamMatches:output_type -> sf.search.v1.SearchMatch
	5, // 8: sf.search.v1.ForkResolver.StreamUndoMatches:output_type -> sf.search.v1.SearchMatch
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sf_search_v1_search_proto_init() }
func file_sf_search_v1_search_proto_init() {
	if File_sf_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_search_v1_search_proto_rawDesc), len(file_sf_search_v1_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_sf_search_v1_search_proto_goTypes,
		DependencyIndexes: file_sf_search_v1_search_proto_depIdxs,
		EnumInfos:         file_sf_search_v1_search_proto_enumTypes,
		MessageInfos:      file_sf_search_v1_search_proto_msgTypes,
	}.Build()
	File_sf_search_v1_search_proto = out.File
	file_sf_search_v1_search_proto_goTypes = nil
	file_sf_search_v1_search_proto_depIdxs = nil
}
