// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/codecs/deth/deth.proto

package deth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionTraceStatus int32

const (
	TransactionTraceStatus_UNKNOWN   TransactionTraceStatus = 0
	TransactionTraceStatus_SUCCEEDED TransactionTraceStatus = 1
	TransactionTraceStatus_FAILED    TransactionTraceStatus = 2
	TransactionTraceStatus_REVERTED  TransactionTraceStatus = 3
)

var TransactionTraceStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCEEDED",
	2: "FAILED",
	3: "REVERTED",
}

var TransactionTraceStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"SUCCEEDED": 1,
	"FAILED":    2,
	"REVERTED":  3,
}

func (x TransactionTraceStatus) String() string {
	return proto.EnumName(TransactionTraceStatus_name, int32(x))
}

func (TransactionTraceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{0}
}

type CallType int32

const (
	CallType_UNSPECIFIED CallType = 0
	CallType_CALL        CallType = 1
	CallType_CALLCODE    CallType = 2
	CallType_DELEGATE    CallType = 3
	CallType_STATIC      CallType = 4
	CallType_CREATE      CallType = 5
)

var CallType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "CALL",
	2: "CALLCODE",
	3: "DELEGATE",
	4: "STATIC",
	5: "CREATE",
}

var CallType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"CALL":        1,
	"CALLCODE":    2,
	"DELEGATE":    3,
	"STATIC":      4,
	"CREATE":      5,
}

func (x CallType) String() string {
	return proto.EnumName(CallType_name, int32(x))
}

func (CallType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{1}
}

type TransactionState_Transition int32

const (
	TransactionState_TRANS_INIT      TransactionState_Transition = 0
	TransactionState_TRANS_POOLED    TransactionState_Transition = 1
	TransactionState_TRANS_MINED     TransactionState_Transition = 2
	TransactionState_TRANS_FORKED    TransactionState_Transition = 3
	TransactionState_TRANS_CONFIRMED TransactionState_Transition = 4
	TransactionState_TRANS_REPLACED  TransactionState_Transition = 5
)

var TransactionState_Transition_name = map[int32]string{
	0: "TRANS_INIT",
	1: "TRANS_POOLED",
	2: "TRANS_MINED",
	3: "TRANS_FORKED",
	4: "TRANS_CONFIRMED",
	5: "TRANS_REPLACED",
}

var TransactionState_Transition_value = map[string]int32{
	"TRANS_INIT":      0,
	"TRANS_POOLED":    1,
	"TRANS_MINED":     2,
	"TRANS_FORKED":    3,
	"TRANS_CONFIRMED": 4,
	"TRANS_REPLACED":  5,
}

func (x TransactionState_Transition) String() string {
	return proto.EnumName(TransactionState_Transition_name, int32(x))
}

func (TransactionState_Transition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{6, 0}
}

type TransactionState_State int32

const (
	TransactionState_STATE_UNKNOWN  TransactionState_State = 0
	TransactionState_STATE_PENDING  TransactionState_State = 1
	TransactionState_STATE_IN_BLOCK TransactionState_State = 2
	TransactionState_STATE_REPLACED TransactionState_State = 3
)

var TransactionState_State_name = map[int32]string{
	0: "STATE_UNKNOWN",
	1: "STATE_PENDING",
	2: "STATE_IN_BLOCK",
	3: "STATE_REPLACED",
}

var TransactionState_State_value = map[string]int32{
	"STATE_UNKNOWN":  0,
	"STATE_PENDING":  1,
	"STATE_IN_BLOCK": 2,
	"STATE_REPLACED": 3,
}

func (x TransactionState_State) String() string {
	return proto.EnumName(TransactionState_State_name, int32(x))
}

func (TransactionState_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{6, 1}
}

// Obtain all balanche change reasons under deep mind repository:
//
//     ack -ho 'BalanceChangeReason\(".*"\)' | grep -Eo '".*"' | sort | uniq
type BalanceChange_Reason int32

const (
	BalanceChange_REASON_UNKNOWN                BalanceChange_Reason = 0
	BalanceChange_REASON_REWARD_MINE_UNCLE      BalanceChange_Reason = 1
	BalanceChange_REASON_REWARD_MINE_BLOCK      BalanceChange_Reason = 2
	BalanceChange_REASON_DAO_REFUND_CONTRACT    BalanceChange_Reason = 3
	BalanceChange_REASON_DAO_ADJUST_BALANCE     BalanceChange_Reason = 4
	BalanceChange_REASON_TRANSFER               BalanceChange_Reason = 5
	BalanceChange_REASON_GENESIS_BALANCE        BalanceChange_Reason = 6
	BalanceChange_REASON_GAS_BUY                BalanceChange_Reason = 7
	BalanceChange_REASON_REWARD_TRANSACTION_FEE BalanceChange_Reason = 8
	BalanceChange_REASON_GAS_REFUND             BalanceChange_Reason = 9
	BalanceChange_REASON_TOUCH_ACCOUNT          BalanceChange_Reason = 10
	BalanceChange_REASON_SUICIDE_REFUND         BalanceChange_Reason = 11
	BalanceChange_REASON_SUICIDE_WITHDRAW       BalanceChange_Reason = 13
	BalanceChange_REASON_CALL_BALANCE_OVERRIDE  BalanceChange_Reason = 12
)

var BalanceChange_Reason_name = map[int32]string{
	0:  "REASON_UNKNOWN",
	1:  "REASON_REWARD_MINE_UNCLE",
	2:  "REASON_REWARD_MINE_BLOCK",
	3:  "REASON_DAO_REFUND_CONTRACT",
	4:  "REASON_DAO_ADJUST_BALANCE",
	5:  "REASON_TRANSFER",
	6:  "REASON_GENESIS_BALANCE",
	7:  "REASON_GAS_BUY",
	8:  "REASON_REWARD_TRANSACTION_FEE",
	9:  "REASON_GAS_REFUND",
	10: "REASON_TOUCH_ACCOUNT",
	11: "REASON_SUICIDE_REFUND",
	13: "REASON_SUICIDE_WITHDRAW",
	12: "REASON_CALL_BALANCE_OVERRIDE",
}

var BalanceChange_Reason_value = map[string]int32{
	"REASON_UNKNOWN":                0,
	"REASON_REWARD_MINE_UNCLE":      1,
	"REASON_REWARD_MINE_BLOCK":      2,
	"REASON_DAO_REFUND_CONTRACT":    3,
	"REASON_DAO_ADJUST_BALANCE":     4,
	"REASON_TRANSFER":               5,
	"REASON_GENESIS_BALANCE":        6,
	"REASON_GAS_BUY":                7,
	"REASON_REWARD_TRANSACTION_FEE": 8,
	"REASON_GAS_REFUND":             9,
	"REASON_TOUCH_ACCOUNT":          10,
	"REASON_SUICIDE_REFUND":         11,
	"REASON_SUICIDE_WITHDRAW":       13,
	"REASON_CALL_BALANCE_OVERRIDE":  12,
}

func (x BalanceChange_Reason) String() string {
	return proto.EnumName(BalanceChange_Reason_name, int32(x))
}

func (BalanceChange_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{13, 0}
}

// Obtain all gas change reasons under deep mind repository:
//
//     ack -ho 'GasChangeReason\(".*"\)' | grep -Eo '".*"' | sort | uniq
type GasChange_Reason int32

const (
	GasChange_REASON_UNKNOWN                GasChange_Reason = 0
	GasChange_REASON_CALL                   GasChange_Reason = 1
	GasChange_REASON_CALL_CODE              GasChange_Reason = 2
	GasChange_REASON_CALL_DATA_COPY         GasChange_Reason = 3
	GasChange_REASON_CODE_COPY              GasChange_Reason = 4
	GasChange_REASON_CODE_STORAGE           GasChange_Reason = 5
	GasChange_REASON_CONTRACT_CREATION      GasChange_Reason = 6
	GasChange_REASON_CONTRACT_CREATION2     GasChange_Reason = 7
	GasChange_REASON_DELEGATE_CALL          GasChange_Reason = 8
	GasChange_REASON_EVENT_LOG              GasChange_Reason = 9
	GasChange_REASON_EXT_CODE_COPY          GasChange_Reason = 10
	GasChange_REASON_FAILED_EXECUTION       GasChange_Reason = 11
	GasChange_REASON_INTRINSIC_GAS          GasChange_Reason = 12
	GasChange_REASON_PRECOMPILED_CONTRACT   GasChange_Reason = 13
	GasChange_REASON_REFUND_AFTER_EXECUTION GasChange_Reason = 14
	GasChange_REASON_RETURN                 GasChange_Reason = 15
	GasChange_REASON_RETURN_DATA_COPY       GasChange_Reason = 16
	GasChange_REASON_REVERT                 GasChange_Reason = 17
	GasChange_REASON_SELF_DESTRUCT          GasChange_Reason = 18
	GasChange_REASON_STATIC_CALL            GasChange_Reason = 19
)

var GasChange_Reason_name = map[int32]string{
	0:  "REASON_UNKNOWN",
	1:  "REASON_CALL",
	2:  "REASON_CALL_CODE",
	3:  "REASON_CALL_DATA_COPY",
	4:  "REASON_CODE_COPY",
	5:  "REASON_CODE_STORAGE",
	6:  "REASON_CONTRACT_CREATION",
	7:  "REASON_CONTRACT_CREATION2",
	8:  "REASON_DELEGATE_CALL",
	9:  "REASON_EVENT_LOG",
	10: "REASON_EXT_CODE_COPY",
	11: "REASON_FAILED_EXECUTION",
	12: "REASON_INTRINSIC_GAS",
	13: "REASON_PRECOMPILED_CONTRACT",
	14: "REASON_REFUND_AFTER_EXECUTION",
	15: "REASON_RETURN",
	16: "REASON_RETURN_DATA_COPY",
	17: "REASON_REVERT",
	18: "REASON_SELF_DESTRUCT",
	19: "REASON_STATIC_CALL",
}

var GasChange_Reason_value = map[string]int32{
	"REASON_UNKNOWN":                0,
	"REASON_CALL":                   1,
	"REASON_CALL_CODE":              2,
	"REASON_CALL_DATA_COPY":         3,
	"REASON_CODE_COPY":              4,
	"REASON_CODE_STORAGE":           5,
	"REASON_CONTRACT_CREATION":      6,
	"REASON_CONTRACT_CREATION2":     7,
	"REASON_DELEGATE_CALL":          8,
	"REASON_EVENT_LOG":              9,
	"REASON_EXT_CODE_COPY":          10,
	"REASON_FAILED_EXECUTION":       11,
	"REASON_INTRINSIC_GAS":          12,
	"REASON_PRECOMPILED_CONTRACT":   13,
	"REASON_REFUND_AFTER_EXECUTION": 14,
	"REASON_RETURN":                 15,
	"REASON_RETURN_DATA_COPY":       16,
	"REASON_REVERT":                 17,
	"REASON_SELF_DESTRUCT":          18,
	"REASON_STATIC_CALL":            19,
}

func (x GasChange_Reason) String() string {
	return proto.EnumName(GasChange_Reason_name, int32(x))
}

func (GasChange_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{16, 0}
}

// Obtain all gas change reasons under deep mind repository:
//
//     ack -ho 'GasEventID\(".*"\)' | grep -Eo '".*"' | sort | uniq
type GasEvent_Id int32

const (
	GasEvent_ID_UNKNOWN     GasEvent_Id = 0
	GasEvent_ID_AFTER_CALL  GasEvent_Id = 1
	GasEvent_ID_BEFORE_CALL GasEvent_Id = 2
)

var GasEvent_Id_name = map[int32]string{
	0: "ID_UNKNOWN",
	1: "ID_AFTER_CALL",
	2: "ID_BEFORE_CALL",
}

var GasEvent_Id_value = map[string]int32{
	"ID_UNKNOWN":     0,
	"ID_AFTER_CALL":  1,
	"ID_BEFORE_CALL": 2,
}

func (x GasEvent_Id) String() string {
	return proto.EnumName(GasEvent_Id_name, int32(x))
}

func (GasEvent_Id) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{17, 0}
}

type Block struct {
	Ver                  int32               `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Hash                 []byte              `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               uint64              `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Size                 uint64              `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Header               *BlockHeader        `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Uncles               []*BlockHeader      `protobuf:"bytes,6,rep,name=uncles,proto3" json:"uncles,omitempty"`
	TransactionTraces    []*TransactionTrace `protobuf:"bytes,10,rep,name=transaction_traces,json=transactionTraces,proto3" json:"transaction_traces,omitempty"`
	BalanceChanges       []*BalanceChange    `protobuf:"bytes,11,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetUncles() []*BlockHeader {
	if m != nil {
		return m.Uncles
	}
	return nil
}

func (m *Block) GetTransactionTraces() []*TransactionTrace {
	if m != nil {
		return m.TransactionTraces
	}
	return nil
}

func (m *Block) GetBalanceChanges() []*BalanceChange {
	if m != nil {
		return m.BalanceChanges
	}
	return nil
}

type TransactionRefs struct {
	Hashes               [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRefs) Reset()         { *m = TransactionRefs{} }
func (m *TransactionRefs) String() string { return proto.CompactTextString(m) }
func (*TransactionRefs) ProtoMessage()    {}
func (*TransactionRefs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{1}
}

func (m *TransactionRefs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRefs.Unmarshal(m, b)
}
func (m *TransactionRefs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRefs.Marshal(b, m, deterministic)
}
func (m *TransactionRefs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRefs.Merge(m, src)
}
func (m *TransactionRefs) XXX_Size() int {
	return xxx_messageInfo_TransactionRefs.Size(m)
}
func (m *TransactionRefs) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRefs.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRefs proto.InternalMessageInfo

func (m *TransactionRefs) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type UnclesHeaders struct {
	Uncles               []*BlockHeader `protobuf:"bytes,1,rep,name=uncles,proto3" json:"uncles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UnclesHeaders) Reset()         { *m = UnclesHeaders{} }
func (m *UnclesHeaders) String() string { return proto.CompactTextString(m) }
func (*UnclesHeaders) ProtoMessage()    {}
func (*UnclesHeaders) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{2}
}

func (m *UnclesHeaders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnclesHeaders.Unmarshal(m, b)
}
func (m *UnclesHeaders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnclesHeaders.Marshal(b, m, deterministic)
}
func (m *UnclesHeaders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnclesHeaders.Merge(m, src)
}
func (m *UnclesHeaders) XXX_Size() int {
	return xxx_messageInfo_UnclesHeaders.Size(m)
}
func (m *UnclesHeaders) XXX_DiscardUnknown() {
	xxx_messageInfo_UnclesHeaders.DiscardUnknown(m)
}

var xxx_messageInfo_UnclesHeaders proto.InternalMessageInfo

func (m *UnclesHeaders) GetUncles() []*BlockHeader {
	if m != nil {
		return m.Uncles
	}
	return nil
}

type BlockRef struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number               uint64   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRef) Reset()         { *m = BlockRef{} }
func (m *BlockRef) String() string { return proto.CompactTextString(m) }
func (*BlockRef) ProtoMessage()    {}
func (*BlockRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{3}
}

func (m *BlockRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRef.Unmarshal(m, b)
}
func (m *BlockRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRef.Marshal(b, m, deterministic)
}
func (m *BlockRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRef.Merge(m, src)
}
func (m *BlockRef) XXX_Size() int {
	return xxx_messageInfo_BlockRef.Size(m)
}
func (m *BlockRef) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRef.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRef proto.InternalMessageInfo

func (m *BlockRef) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockRef) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type BlockHeader struct {
	ParentHash           []byte               `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	UncleHash            []byte               `protobuf:"bytes,2,opt,name=uncle_hash,json=uncleHash,proto3" json:"uncle_hash,omitempty"`
	Coinbase             []byte               `protobuf:"bytes,3,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	StateRoot            []byte               `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TransactionsRoot     []byte               `protobuf:"bytes,5,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty"`
	ReceiptRoot          []byte               `protobuf:"bytes,6,opt,name=receipt_root,json=receiptRoot,proto3" json:"receipt_root,omitempty"`
	LogsBloom            []byte               `protobuf:"bytes,7,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Difficulty           *BigInt              `protobuf:"bytes,8,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Number               uint64               `protobuf:"varint,9,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit             uint64               `protobuf:"varint,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed              uint64               `protobuf:"varint,11,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData            []byte               `protobuf:"bytes,13,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	MixHash              []byte               `protobuf:"bytes,14,opt,name=mix_hash,json=mixHash,proto3" json:"mix_hash,omitempty"`
	Nonce                uint64               `protobuf:"varint,15,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Hash                 []byte               `protobuf:"bytes,16,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{4}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetUncleHash() []byte {
	if m != nil {
		return m.UncleHash
	}
	return nil
}

func (m *BlockHeader) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeader) GetTransactionsRoot() []byte {
	if m != nil {
		return m.TransactionsRoot
	}
	return nil
}

func (m *BlockHeader) GetReceiptRoot() []byte {
	if m != nil {
		return m.ReceiptRoot
	}
	return nil
}

func (m *BlockHeader) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *BlockHeader) GetDifficulty() *BigInt {
	if m != nil {
		return m.Difficulty
	}
	return nil
}

func (m *BlockHeader) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHeader) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *BlockHeader) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *BlockHeader) GetMixHash() []byte {
	if m != nil {
		return m.MixHash
	}
	return nil
}

func (m *BlockHeader) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BigInt struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInt) Reset()         { *m = BigInt{} }
func (m *BigInt) String() string { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()    {}
func (*BigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{5}
}

func (m *BigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInt.Unmarshal(m, b)
}
func (m *BigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInt.Marshal(b, m, deterministic)
}
func (m *BigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInt.Merge(m, src)
}
func (m *BigInt) XXX_Size() int {
	return xxx_messageInfo_BigInt.Size(m)
}
func (m *BigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInt.DiscardUnknown(m)
}

var xxx_messageInfo_BigInt proto.InternalMessageInfo

func (m *BigInt) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type TransactionState struct {
	PreviousState        TransactionState_State      `protobuf:"varint,1,opt,name=previous_state,json=previousState,proto3,enum=dfuse.codecs.deth.TransactionState_State" json:"previous_state,omitempty"`
	CurrentState         TransactionState_State      `protobuf:"varint,2,opt,name=current_state,json=currentState,proto3,enum=dfuse.codecs.deth.TransactionState_State" json:"current_state,omitempty"`
	Transition           TransactionState_Transition `protobuf:"varint,10,opt,name=transition,proto3,enum=dfuse.codecs.deth.TransactionState_Transition" json:"transition,omitempty"`
	TransactionId        string                      `protobuf:"bytes,11,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Trx                  *Transaction                `protobuf:"bytes,3,opt,name=trx,proto3" json:"trx,omitempty"`
	BlockHeader          *BlockHeader                `protobuf:"bytes,4,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	TransactionTraces    *TransactionTrace           `protobuf:"bytes,5,opt,name=transaction_traces,json=transactionTraces,proto3" json:"transaction_traces,omitempty"`
	Confirmation         uint64                      `protobuf:"varint,6,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	HeadBlockHeader      *BlockHeader                `protobuf:"bytes,7,opt,name=head_block_header,json=headBlockHeader,proto3" json:"head_block_header,omitempty"`
	ReplacedById         string                      `protobuf:"bytes,8,opt,name=replaced_by_id,json=replacedById,proto3" json:"replaced_by_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TransactionState) Reset()         { *m = TransactionState{} }
func (m *TransactionState) String() string { return proto.CompactTextString(m) }
func (*TransactionState) ProtoMessage()    {}
func (*TransactionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{6}
}

func (m *TransactionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionState.Unmarshal(m, b)
}
func (m *TransactionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionState.Marshal(b, m, deterministic)
}
func (m *TransactionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionState.Merge(m, src)
}
func (m *TransactionState) XXX_Size() int {
	return xxx_messageInfo_TransactionState.Size(m)
}
func (m *TransactionState) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionState.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionState proto.InternalMessageInfo

func (m *TransactionState) GetPreviousState() TransactionState_State {
	if m != nil {
		return m.PreviousState
	}
	return TransactionState_STATE_UNKNOWN
}

func (m *TransactionState) GetCurrentState() TransactionState_State {
	if m != nil {
		return m.CurrentState
	}
	return TransactionState_STATE_UNKNOWN
}

func (m *TransactionState) GetTransition() TransactionState_Transition {
	if m != nil {
		return m.Transition
	}
	return TransactionState_TRANS_INIT
}

func (m *TransactionState) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *TransactionState) GetTrx() *Transaction {
	if m != nil {
		return m.Trx
	}
	return nil
}

func (m *TransactionState) GetBlockHeader() *BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

func (m *TransactionState) GetTransactionTraces() *TransactionTrace {
	if m != nil {
		return m.TransactionTraces
	}
	return nil
}

func (m *TransactionState) GetConfirmation() uint64 {
	if m != nil {
		return m.Confirmation
	}
	return 0
}

func (m *TransactionState) GetHeadBlockHeader() *BlockHeader {
	if m != nil {
		return m.HeadBlockHeader
	}
	return nil
}

func (m *TransactionState) GetReplacedById() string {
	if m != nil {
		return m.ReplacedById
	}
	return ""
}

// A Transaction not yet in block
type Transaction struct {
	// consensus
	To       []byte  `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Nonce    uint64  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasPrice *BigInt `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit uint64  `protobuf:"varint,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Value    *BigInt `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Input    []byte  `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	V        []byte  `protobuf:"bytes,7,opt,name=v,proto3" json:"v,omitempty"`
	R        []byte  `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S        []byte  `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	// meta
	Hash                 []byte   `protobuf:"bytes,21,opt,name=hash,proto3" json:"hash,omitempty"`
	From                 []byte   `protobuf:"bytes,22,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{7}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetGasPrice() *BigInt {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *Transaction) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Transaction) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Transaction) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *Transaction) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Transaction) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

type TransactionTrace struct {
	// consensus
	To       []byte  `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Nonce    uint64  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasPrice *BigInt `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit uint64  `protobuf:"varint,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Value    *BigInt `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Input    []byte  `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	V        []byte  `protobuf:"bytes,7,opt,name=v,proto3" json:"v,omitempty"`
	R        []byte  `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S        []byte  `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	GasUsed  uint64  `protobuf:"varint,10,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// meta
	Index                uint32                 `protobuf:"varint,20,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 []byte                 `protobuf:"bytes,21,opt,name=hash,proto3" json:"hash,omitempty"`
	From                 []byte                 `protobuf:"bytes,22,opt,name=from,proto3" json:"from,omitempty"`
	ReturnData           []byte                 `protobuf:"bytes,23,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	PublicKey            []byte                 `protobuf:"bytes,24,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status               TransactionTraceStatus `protobuf:"varint,30,opt,name=status,proto3,enum=dfuse.codecs.deth.TransactionTraceStatus" json:"status,omitempty"`
	Receipt              *TransactionReceipt    `protobuf:"bytes,31,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Calls                []*Call                `protobuf:"bytes,32,rep,name=calls,proto3" json:"calls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TransactionTrace) Reset()         { *m = TransactionTrace{} }
func (m *TransactionTrace) String() string { return proto.CompactTextString(m) }
func (*TransactionTrace) ProtoMessage()    {}
func (*TransactionTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{8}
}

func (m *TransactionTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionTrace.Unmarshal(m, b)
}
func (m *TransactionTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionTrace.Marshal(b, m, deterministic)
}
func (m *TransactionTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionTrace.Merge(m, src)
}
func (m *TransactionTrace) XXX_Size() int {
	return xxx_messageInfo_TransactionTrace.Size(m)
}
func (m *TransactionTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionTrace.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionTrace proto.InternalMessageInfo

func (m *TransactionTrace) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransactionTrace) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionTrace) GetGasPrice() *BigInt {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *TransactionTrace) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *TransactionTrace) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TransactionTrace) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *TransactionTrace) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *TransactionTrace) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *TransactionTrace) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *TransactionTrace) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *TransactionTrace) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TransactionTrace) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *TransactionTrace) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransactionTrace) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

func (m *TransactionTrace) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *TransactionTrace) GetStatus() TransactionTraceStatus {
	if m != nil {
		return m.Status
	}
	return TransactionTraceStatus_UNKNOWN
}

func (m *TransactionTrace) GetReceipt() *TransactionReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *TransactionTrace) GetCalls() []*Call {
	if m != nil {
		return m.Calls
	}
	return nil
}

type TransactionReceipt struct {
	// consensus
	StateRoot            []byte   `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	CumulativeGasUsed    uint64   `protobuf:"varint,2,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty"`
	LogsBloom            []byte   `protobuf:"bytes,3,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionReceipt) Reset()         { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()    {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{9}
}

func (m *TransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceipt.Unmarshal(m, b)
}
func (m *TransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceipt.Marshal(b, m, deterministic)
}
func (m *TransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceipt.Merge(m, src)
}
func (m *TransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_TransactionReceipt.Size(m)
}
func (m *TransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceipt proto.InternalMessageInfo

func (m *TransactionReceipt) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *TransactionReceipt) GetCumulativeGasUsed() uint64 {
	if m != nil {
		return m.CumulativeGasUsed
	}
	return 0
}

func (m *TransactionReceipt) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *TransactionReceipt) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Log struct {
	// consensus
	Address []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics  [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data    []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// supplement
	Index                uint32   `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	BlockIndex           uint32   `protobuf:"varint,6,opt,name=blockIndex,proto3" json:"blockIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{10}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Log) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Log) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Log) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Log) GetBlockIndex() uint32 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

type Call struct {
	Index        uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ParentIndex  uint32   `protobuf:"varint,2,opt,name=parent_index,json=parentIndex,proto3" json:"parent_index,omitempty"`
	Depth        uint32   `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	CallType     CallType `protobuf:"varint,4,opt,name=call_type,json=callType,proto3,enum=dfuse.codecs.deth.CallType" json:"call_type,omitempty"`
	Caller       []byte   `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"`
	Address      []byte   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Value        *BigInt  `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	GasLimit     uint64   `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasConsumed  uint64   `protobuf:"varint,9,opt,name=gas_consumed,json=gasConsumed,proto3" json:"gas_consumed,omitempty"`
	ReturnData   []byte   `protobuf:"bytes,13,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	Input        []byte   `protobuf:"bytes,14,opt,name=input,proto3" json:"input,omitempty"`
	ExecutedCode bool     `protobuf:"varint,15,opt,name=executed_code,json=executedCode,proto3" json:"executed_code,omitempty"`
	Suicide      bool     `protobuf:"varint,16,opt,name=suicide,proto3" json:"suicide,omitempty"`
	// hex representation of the hash -> preimage
	KeccakPreimages map[string]string `protobuf:"bytes,20,rep,name=keccak_preimages,json=keccakPreimages,proto3" json:"keccak_preimages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StorageChanges  []*StorageChange  `protobuf:"bytes,21,rep,name=storage_changes,json=storageChanges,proto3" json:"storage_changes,omitempty"`
	BalanceChanges  []*BalanceChange  `protobuf:"bytes,22,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	NonceChanges    []*NonceChange    `protobuf:"bytes,24,rep,name=nonce_changes,json=nonceChanges,proto3" json:"nonce_changes,omitempty"`
	Logs            []*Log            `protobuf:"bytes,25,rep,name=logs,proto3" json:"logs,omitempty"`
	CodeChanges     []*CodeChange     `protobuf:"bytes,26,rep,name=code_changes,json=codeChanges,proto3" json:"code_changes,omitempty"`
	CreatedAccounts [][]byte          `protobuf:"bytes,27,rep,name=created_accounts,json=createdAccounts,proto3" json:"created_accounts,omitempty"`
	GasChanges      []*GasChange      `protobuf:"bytes,28,rep,name=gas_changes,json=gasChanges,proto3" json:"gas_changes,omitempty"`
	GasEvents       []*GasEvent       `protobuf:"bytes,29,rep,name=gas_events,json=gasEvents,proto3" json:"gas_events,omitempty"`
	// In Ethereum, a call can be either:
	// - Successfull, execution passes without any problem encountered
	// - Failed, execution failed, and remaining gas should be consumed
	// - Reverted, execution failed, but only gas consumed so far is billed, remaining gas is refunded
	//
	// When a call is either `failed` or `reverted`, the `status_failed` field
	// below is set to `true`. If the status is `reverted`, then both `status_failed`
	// and `status_reverted` are going to be set to `true`.
	StatusFailed   bool `protobuf:"varint,10,opt,name=status_failed,json=statusFailed,proto3" json:"status_failed,omitempty"`
	StatusReverted bool `protobuf:"varint,12,opt,name=status_reverted,json=statusReverted,proto3" json:"status_reverted,omitempty"`
	// Populated when a call either failed or reverted, so when `status_failed == true`,
	// see above for details about those flags.
	FailureReason string `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// This field represents wheter or not the state changes performed
	// by this call were correctly recorded by the blockchain.
	//
	// On Ethereum, a transaction can record state changes even if some
	// of its inner nested calls failed. This is problematic however since
	// a call will invalidate all its state changes as well as all state
	// changes performed by its child call. This means that even if a call
	// has a status of `SUCCESS`, the chain might have reverted all the state
	// changes it performed.
	//
	// ```
	//   Trx 1
	//    Call #1 <Failed>
	//      Call #2 <Execution Success>
	//      Call #3 <Execution Success>
	//      |--- Failure here
	//    Call #4
	// ```
	//
	// In the transaction above, while Call #2 and Call #3 would have the
	// status `EXECUTED`
	StateReverted        bool     `protobuf:"varint,30,opt,name=state_reverted,json=stateReverted,proto3" json:"state_reverted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{11}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Call) GetParentIndex() uint32 {
	if m != nil {
		return m.ParentIndex
	}
	return 0
}

func (m *Call) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *Call) GetCallType() CallType {
	if m != nil {
		return m.CallType
	}
	return CallType_UNSPECIFIED
}

func (m *Call) GetCaller() []byte {
	if m != nil {
		return m.Caller
	}
	return nil
}

func (m *Call) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Call) GetValue() *BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Call) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Call) GetGasConsumed() uint64 {
	if m != nil {
		return m.GasConsumed
	}
	return 0
}

func (m *Call) GetReturnData() []byte {
	if m != nil {
		return m.ReturnData
	}
	return nil
}

func (m *Call) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Call) GetExecutedCode() bool {
	if m != nil {
		return m.ExecutedCode
	}
	return false
}

func (m *Call) GetSuicide() bool {
	if m != nil {
		return m.Suicide
	}
	return false
}

func (m *Call) GetKeccakPreimages() map[string]string {
	if m != nil {
		return m.KeccakPreimages
	}
	return nil
}

func (m *Call) GetStorageChanges() []*StorageChange {
	if m != nil {
		return m.StorageChanges
	}
	return nil
}

func (m *Call) GetBalanceChanges() []*BalanceChange {
	if m != nil {
		return m.BalanceChanges
	}
	return nil
}

func (m *Call) GetNonceChanges() []*NonceChange {
	if m != nil {
		return m.NonceChanges
	}
	return nil
}

func (m *Call) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *Call) GetCodeChanges() []*CodeChange {
	if m != nil {
		return m.CodeChanges
	}
	return nil
}

func (m *Call) GetCreatedAccounts() [][]byte {
	if m != nil {
		return m.CreatedAccounts
	}
	return nil
}

func (m *Call) GetGasChanges() []*GasChange {
	if m != nil {
		return m.GasChanges
	}
	return nil
}

func (m *Call) GetGasEvents() []*GasEvent {
	if m != nil {
		return m.GasEvents
	}
	return nil
}

func (m *Call) GetStatusFailed() bool {
	if m != nil {
		return m.StatusFailed
	}
	return false
}

func (m *Call) GetStatusReverted() bool {
	if m != nil {
		return m.StatusReverted
	}
	return false
}

func (m *Call) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func (m *Call) GetStateReverted() bool {
	if m != nil {
		return m.StateReverted
	}
	return false
}

type StorageChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	OldValue             []byte   `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             []byte   `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageChange) Reset()         { *m = StorageChange{} }
func (m *StorageChange) String() string { return proto.CompactTextString(m) }
func (*StorageChange) ProtoMessage()    {}
func (*StorageChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{12}
}

func (m *StorageChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageChange.Unmarshal(m, b)
}
func (m *StorageChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageChange.Marshal(b, m, deterministic)
}
func (m *StorageChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageChange.Merge(m, src)
}
func (m *StorageChange) XXX_Size() int {
	return xxx_messageInfo_StorageChange.Size(m)
}
func (m *StorageChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageChange.DiscardUnknown(m)
}

var xxx_messageInfo_StorageChange proto.InternalMessageInfo

func (m *StorageChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *StorageChange) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *StorageChange) GetOldValue() []byte {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *StorageChange) GetNewValue() []byte {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type BalanceChange struct {
	Address              []byte               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldValue             *BigInt              `protobuf:"bytes,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             *BigInt              `protobuf:"bytes,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	Reason               BalanceChange_Reason `protobuf:"varint,4,opt,name=reason,proto3,enum=dfuse.codecs.deth.BalanceChange_Reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BalanceChange) Reset()         { *m = BalanceChange{} }
func (m *BalanceChange) String() string { return proto.CompactTextString(m) }
func (*BalanceChange) ProtoMessage()    {}
func (*BalanceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{13}
}

func (m *BalanceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceChange.Unmarshal(m, b)
}
func (m *BalanceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceChange.Marshal(b, m, deterministic)
}
func (m *BalanceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceChange.Merge(m, src)
}
func (m *BalanceChange) XXX_Size() int {
	return xxx_messageInfo_BalanceChange.Size(m)
}
func (m *BalanceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceChange.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceChange proto.InternalMessageInfo

func (m *BalanceChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BalanceChange) GetOldValue() *BigInt {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *BalanceChange) GetNewValue() *BigInt {
	if m != nil {
		return m.NewValue
	}
	return nil
}

func (m *BalanceChange) GetReason() BalanceChange_Reason {
	if m != nil {
		return m.Reason
	}
	return BalanceChange_REASON_UNKNOWN
}

type NonceChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldValue             uint64   `protobuf:"varint,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             uint64   `protobuf:"varint,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonceChange) Reset()         { *m = NonceChange{} }
func (m *NonceChange) String() string { return proto.CompactTextString(m) }
func (*NonceChange) ProtoMessage()    {}
func (*NonceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{14}
}

func (m *NonceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonceChange.Unmarshal(m, b)
}
func (m *NonceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonceChange.Marshal(b, m, deterministic)
}
func (m *NonceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceChange.Merge(m, src)
}
func (m *NonceChange) XXX_Size() int {
	return xxx_messageInfo_NonceChange.Size(m)
}
func (m *NonceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceChange.DiscardUnknown(m)
}

var xxx_messageInfo_NonceChange proto.InternalMessageInfo

func (m *NonceChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *NonceChange) GetOldValue() uint64 {
	if m != nil {
		return m.OldValue
	}
	return 0
}

func (m *NonceChange) GetNewValue() uint64 {
	if m != nil {
		return m.NewValue
	}
	return 0
}

type CodeChange struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldHash              []byte   `protobuf:"bytes,2,opt,name=old_hash,json=oldHash,proto3" json:"old_hash,omitempty"`
	OldCode              []byte   `protobuf:"bytes,3,opt,name=old_code,json=oldCode,proto3" json:"old_code,omitempty"`
	NewHash              []byte   `protobuf:"bytes,4,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`
	NewCode              []byte   `protobuf:"bytes,5,opt,name=new_code,json=newCode,proto3" json:"new_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeChange) Reset()         { *m = CodeChange{} }
func (m *CodeChange) String() string { return proto.CompactTextString(m) }
func (*CodeChange) ProtoMessage()    {}
func (*CodeChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{15}
}

func (m *CodeChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeChange.Unmarshal(m, b)
}
func (m *CodeChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeChange.Marshal(b, m, deterministic)
}
func (m *CodeChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeChange.Merge(m, src)
}
func (m *CodeChange) XXX_Size() int {
	return xxx_messageInfo_CodeChange.Size(m)
}
func (m *CodeChange) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeChange.DiscardUnknown(m)
}

var xxx_messageInfo_CodeChange proto.InternalMessageInfo

func (m *CodeChange) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *CodeChange) GetOldHash() []byte {
	if m != nil {
		return m.OldHash
	}
	return nil
}

func (m *CodeChange) GetOldCode() []byte {
	if m != nil {
		return m.OldCode
	}
	return nil
}

func (m *CodeChange) GetNewHash() []byte {
	if m != nil {
		return m.NewHash
	}
	return nil
}

func (m *CodeChange) GetNewCode() []byte {
	if m != nil {
		return m.NewCode
	}
	return nil
}

// The gas change model represents the reason why some gas cost has occurred.
// The gas is computed per actual op codes. Doing them completely might prove
// overwhelming in most cases.
//
// Hence, we only index some of them, those that are costy like all the calls
// one, log events, return data, etc.
type GasChange struct {
	OldValue             uint64           `protobuf:"varint,1,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             uint64           `protobuf:"varint,2,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	Reason               GasChange_Reason `protobuf:"varint,3,opt,name=reason,proto3,enum=dfuse.codecs.deth.GasChange_Reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GasChange) Reset()         { *m = GasChange{} }
func (m *GasChange) String() string { return proto.CompactTextString(m) }
func (*GasChange) ProtoMessage()    {}
func (*GasChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{16}
}

func (m *GasChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasChange.Unmarshal(m, b)
}
func (m *GasChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasChange.Marshal(b, m, deterministic)
}
func (m *GasChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasChange.Merge(m, src)
}
func (m *GasChange) XXX_Size() int {
	return xxx_messageInfo_GasChange.Size(m)
}
func (m *GasChange) XXX_DiscardUnknown() {
	xxx_messageInfo_GasChange.DiscardUnknown(m)
}

var xxx_messageInfo_GasChange proto.InternalMessageInfo

func (m *GasChange) GetOldValue() uint64 {
	if m != nil {
		return m.OldValue
	}
	return 0
}

func (m *GasChange) GetNewValue() uint64 {
	if m != nil {
		return m.NewValue
	}
	return 0
}

func (m *GasChange) GetReason() GasChange_Reason {
	if m != nil {
		return m.Reason
	}
	return GasChange_REASON_UNKNOWN
}

// Gas events are emitted to faciliate gas tracking avoid the execution
// call stack that happens while processing a transaction on the chain.
//
// We currently have events for tracing of gas amount before and after
// each child call.
type GasEvent struct {
	Id                   GasEvent_Id `protobuf:"varint,1,opt,name=id,proto3,enum=dfuse.codecs.deth.GasEvent_Id" json:"id,omitempty"`
	Gas                  uint64      `protobuf:"varint,2,opt,name=gas,proto3" json:"gas,omitempty"`
	LinkedCallIndex      uint64      `protobuf:"varint,3,opt,name=linked_call_index,json=linkedCallIndex,proto3" json:"linked_call_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GasEvent) Reset()         { *m = GasEvent{} }
func (m *GasEvent) String() string { return proto.CompactTextString(m) }
func (*GasEvent) ProtoMessage()    {}
func (*GasEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f10a8911eca0e2c, []int{17}
}

func (m *GasEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasEvent.Unmarshal(m, b)
}
func (m *GasEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasEvent.Marshal(b, m, deterministic)
}
func (m *GasEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasEvent.Merge(m, src)
}
func (m *GasEvent) XXX_Size() int {
	return xxx_messageInfo_GasEvent.Size(m)
}
func (m *GasEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GasEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GasEvent proto.InternalMessageInfo

func (m *GasEvent) GetId() GasEvent_Id {
	if m != nil {
		return m.Id
	}
	return GasEvent_ID_UNKNOWN
}

func (m *GasEvent) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

func (m *GasEvent) GetLinkedCallIndex() uint64 {
	if m != nil {
		return m.LinkedCallIndex
	}
	return 0
}

func init() {
	proto.RegisterEnum("dfuse.codecs.deth.TransactionTraceStatus", TransactionTraceStatus_name, TransactionTraceStatus_value)
	proto.RegisterEnum("dfuse.codecs.deth.CallType", CallType_name, CallType_value)
	proto.RegisterEnum("dfuse.codecs.deth.TransactionState_Transition", TransactionState_Transition_name, TransactionState_Transition_value)
	proto.RegisterEnum("dfuse.codecs.deth.TransactionState_State", TransactionState_State_name, TransactionState_State_value)
	proto.RegisterEnum("dfuse.codecs.deth.BalanceChange_Reason", BalanceChange_Reason_name, BalanceChange_Reason_value)
	proto.RegisterEnum("dfuse.codecs.deth.GasChange_Reason", GasChange_Reason_name, GasChange_Reason_value)
	proto.RegisterEnum("dfuse.codecs.deth.GasEvent_Id", GasEvent_Id_name, GasEvent_Id_value)
	proto.RegisterType((*Block)(nil), "dfuse.codecs.deth.Block")
	proto.RegisterType((*TransactionRefs)(nil), "dfuse.codecs.deth.TransactionRefs")
	proto.RegisterType((*UnclesHeaders)(nil), "dfuse.codecs.deth.UnclesHeaders")
	proto.RegisterType((*BlockRef)(nil), "dfuse.codecs.deth.BlockRef")
	proto.RegisterType((*BlockHeader)(nil), "dfuse.codecs.deth.BlockHeader")
	proto.RegisterType((*BigInt)(nil), "dfuse.codecs.deth.BigInt")
	proto.RegisterType((*TransactionState)(nil), "dfuse.codecs.deth.TransactionState")
	proto.RegisterType((*Transaction)(nil), "dfuse.codecs.deth.Transaction")
	proto.RegisterType((*TransactionTrace)(nil), "dfuse.codecs.deth.TransactionTrace")
	proto.RegisterType((*TransactionReceipt)(nil), "dfuse.codecs.deth.TransactionReceipt")
	proto.RegisterType((*Log)(nil), "dfuse.codecs.deth.Log")
	proto.RegisterType((*Call)(nil), "dfuse.codecs.deth.Call")
	proto.RegisterMapType((map[string]string)(nil), "dfuse.codecs.deth.Call.KeccakPreimagesEntry")
	proto.RegisterType((*StorageChange)(nil), "dfuse.codecs.deth.StorageChange")
	proto.RegisterType((*BalanceChange)(nil), "dfuse.codecs.deth.BalanceChange")
	proto.RegisterType((*NonceChange)(nil), "dfuse.codecs.deth.NonceChange")
	proto.RegisterType((*CodeChange)(nil), "dfuse.codecs.deth.CodeChange")
	proto.RegisterType((*GasChange)(nil), "dfuse.codecs.deth.GasChange")
	proto.RegisterType((*GasEvent)(nil), "dfuse.codecs.deth.GasEvent")
}

func init() { proto.RegisterFile("dfuse/codecs/deth/deth.proto", fileDescriptor_3f10a8911eca0e2c) }

var fileDescriptor_3f10a8911eca0e2c = []byte{
	// 2493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x59, 0x4f, 0x73, 0xdb, 0xc6,
	0x15, 0x0f, 0xf8, 0x4f, 0xd4, 0x23, 0x48, 0x41, 0x6b, 0x5b, 0x86, 0x24, 0x4b, 0x96, 0x99, 0x66,
	0xe2, 0x38, 0x0d, 0xd5, 0x71, 0x67, 0x3c, 0x69, 0x32, 0x9d, 0x14, 0x02, 0x20, 0x19, 0x31, 0x03,
	0x6a, 0x96, 0xa0, 0x9d, 0xf4, 0x82, 0x01, 0x81, 0x15, 0x85, 0x31, 0x45, 0x70, 0x00, 0x50, 0xb6,
	0x72, 0xeb, 0x4c, 0x2f, 0xed, 0xb1, 0x9f, 0xa0, 0xfd, 0x02, 0xbd, 0xf5, 0x4b, 0xf4, 0xd4, 0x2f,
	0xd0, 0x73, 0xfb, 0x31, 0x3a, 0xfb, 0x07, 0xe4, 0x52, 0xa6, 0x65, 0x25, 0xd7, 0x5e, 0x34, 0xbb,
	0xef, 0xdf, 0x3e, 0xbc, 0xf7, 0x7b, 0x6f, 0xdf, 0x52, 0xf0, 0x20, 0x3a, 0x9b, 0x65, 0xe4, 0x30,
	0x4c, 0x22, 0x12, 0x66, 0x87, 0x11, 0xc9, 0xcf, 0xd9, 0x9f, 0xce, 0x34, 0x4d, 0xf2, 0x04, 0x6d,
	0x32, 0x6e, 0x87, 0x73, 0x3b, 0x94, 0xb1, 0xf3, 0x70, 0x94, 0x24, 0xa3, 0x31, 0x39, 0x64, 0x02,
	0xc3, 0xd9, 0xd9, 0x61, 0x1e, 0x5f, 0x90, 0x2c, 0x0f, 0x2e, 0xa6, 0x5c, 0xa7, 0xfd, 0xdf, 0x12,
	0x54, 0x8f, 0xc6, 0x49, 0xf8, 0x1a, 0x69, 0x50, 0xbe, 0x24, 0xa9, 0xae, 0x1c, 0x28, 0x8f, 0xab,
	0x98, 0x2e, 0x11, 0x82, 0xca, 0x79, 0x90, 0x9d, 0xeb, 0xa5, 0x03, 0xe5, 0xb1, 0x8a, 0xd9, 0x1a,
	0x6d, 0x41, 0x6d, 0x32, 0xbb, 0x18, 0x92, 0x54, 0x2f, 0x1f, 0x28, 0x8f, 0x2b, 0x58, 0xec, 0xa8,
	0x6c, 0x16, 0xff, 0x48, 0xf4, 0x0a, 0xa3, 0xb2, 0x35, 0x7a, 0x06, 0xb5, 0x73, 0x12, 0x44, 0x24,
	0xd5, 0xab, 0x07, 0xca, 0xe3, 0xc6, 0xd3, 0xfd, 0xce, 0x3b, 0x0e, 0x76, 0xd8, 0xd9, 0xcf, 0x99,
	0x14, 0x16, 0xd2, 0x54, 0x6f, 0x36, 0x09, 0xc7, 0x24, 0xd3, 0x6b, 0x07, 0xe5, 0xdb, 0xe8, 0x71,
	0x69, 0x84, 0x01, 0xe5, 0x69, 0x30, 0xc9, 0x82, 0x30, 0x8f, 0x93, 0x89, 0x9f, 0xa7, 0x41, 0x48,
	0x32, 0x1d, 0x98, 0x8d, 0x8f, 0x57, 0xd8, 0xf0, 0x16, 0xc2, 0x1e, 0x95, 0xc5, 0x9b, 0xf9, 0x35,
	0x4a, 0x86, 0x1c, 0xd8, 0x18, 0x06, 0xe3, 0x60, 0x12, 0x12, 0x3f, 0x3c, 0x0f, 0x26, 0x23, 0x92,
	0xe9, 0x0d, 0x66, 0xf0, 0x60, 0x95, 0x53, 0x5c, 0xd2, 0x64, 0x82, 0xb8, 0x35, 0x94, 0xb7, 0x59,
	0xfb, 0x33, 0xd8, 0x90, 0x4e, 0xc4, 0xe4, 0x2c, 0xa3, 0xd1, 0xa4, 0x51, 0x25, 0x99, 0xae, 0x1c,
	0x94, 0x1f, 0xab, 0x58, 0xec, 0xda, 0x27, 0xd0, 0x1c, 0xb0, 0x6f, 0xe2, 0x5f, 0x98, 0x49, 0x21,
	0x51, 0x7e, 0x4a, 0x48, 0xda, 0xcf, 0xa0, 0xce, 0xc8, 0x98, 0x9c, 0xcd, 0xd3, 0xa9, 0xac, 0x4c,
	0x67, 0x49, 0x4e, 0x67, 0xfb, 0xaf, 0x15, 0x68, 0x48, 0xf6, 0xd0, 0x43, 0x68, 0x4c, 0x83, 0x94,
	0x4c, 0x72, 0x5f, 0x32, 0x01, 0x9c, 0xf4, 0x9c, 0x1a, 0xda, 0x03, 0x60, 0x47, 0xfa, 0x12, 0x62,
	0xd6, 0x19, 0x85, 0xb1, 0x77, 0xa0, 0x1e, 0x26, 0xf1, 0x64, 0x18, 0x64, 0x84, 0x01, 0x47, 0xc5,
	0xf3, 0x3d, 0x55, 0xcd, 0xf2, 0x20, 0x27, 0x7e, 0x9a, 0x24, 0x39, 0x03, 0x90, 0x8a, 0xd7, 0x19,
	0x05, 0x27, 0x49, 0x8e, 0x3e, 0x07, 0x39, 0x2d, 0x19, 0x97, 0xaa, 0x32, 0x29, 0x4d, 0x66, 0x30,
	0xe1, 0x47, 0xa0, 0xa6, 0x24, 0x24, 0xf1, 0x34, 0xe7, 0x72, 0x35, 0x26, 0xd7, 0x10, 0x34, 0x26,
	0xb2, 0x07, 0x30, 0x4e, 0x46, 0x99, 0x3f, 0x1c, 0x27, 0xc9, 0x85, 0xbe, 0xc6, 0x8f, 0xa3, 0x94,
	0x23, 0x4a, 0x40, 0xbf, 0x01, 0x88, 0xe2, 0xb3, 0xb3, 0x38, 0x9c, 0x8d, 0xf3, 0x2b, 0xbd, 0xce,
	0x80, 0xbb, 0xbd, 0x2a, 0xda, 0xf1, 0xc8, 0x99, 0xe4, 0x58, 0x12, 0x96, 0x82, 0xb9, 0xbe, 0x54,
	0x1b, 0xbb, 0xb0, 0x3e, 0x0a, 0x32, 0x7f, 0x1c, 0x5f, 0xc4, 0xb9, 0x0e, 0x8c, 0x55, 0x1f, 0x05,
	0x59, 0x97, 0xee, 0xd1, 0x36, 0xd0, 0xb5, 0x3f, 0xcb, 0x48, 0xa4, 0x37, 0x18, 0x6f, 0x6d, 0x14,
	0x64, 0x83, 0x8c, 0x44, 0xe8, 0x4b, 0x58, 0x9f, 0x97, 0xab, 0xae, 0x32, 0x4f, 0x76, 0x3a, 0xbc,
	0xa0, 0x3b, 0x45, 0x41, 0x77, 0xbc, 0x42, 0x02, 0x2f, 0x84, 0xe9, 0x37, 0x92, 0xb7, 0x79, 0x1a,
	0xf8, 0x51, 0x90, 0x07, 0x7a, 0x93, 0x7f, 0x23, 0xa3, 0x58, 0x41, 0x1e, 0xd0, 0x33, 0x2f, 0xe2,
	0xb7, 0x3c, 0x55, 0x2d, 0xc6, 0x5c, 0xbb, 0x88, 0xdf, 0xb2, 0x44, 0xdd, 0x85, 0xea, 0x24, 0x99,
	0x84, 0x44, 0xdf, 0x60, 0xbe, 0xf0, 0xcd, 0x1c, 0x3a, 0xda, 0x02, 0x3a, 0xed, 0x7d, 0xa8, 0xf1,
	0x18, 0x50, 0x9d, 0xe1, 0x55, 0xce, 0xb0, 0x49, 0xd9, 0x7c, 0xd3, 0xfe, 0x77, 0x0d, 0x34, 0x09,
	0xef, 0x7d, 0x9a, 0x50, 0x74, 0x0a, 0xad, 0x69, 0x4a, 0x2e, 0xe3, 0x64, 0x96, 0xf9, 0x2c, 0xc5,
	0x4c, 0xa7, 0xf5, 0xf4, 0xb3, 0x9b, 0xcb, 0x93, 0x29, 0x77, 0xd8, 0x5f, 0xdc, 0x2c, 0x0c, 0x70,
	0x8b, 0x2e, 0x34, 0xc3, 0x59, 0xca, 0xa0, 0xc9, 0x0d, 0x96, 0x7e, 0xaa, 0x41, 0x55, 0xe8, 0x17,
	0xf6, 0x80, 0xa1, 0x2a, 0xa6, 0x62, 0x2c, 0x5b, 0xad, 0xa7, 0x9d, 0xdb, 0x18, 0xf3, 0xe6, 0x5a,
	0x58, 0xb2, 0x80, 0x3e, 0x81, 0x96, 0xdc, 0x94, 0x62, 0x9e, 0xe5, 0x75, 0xdc, 0x94, 0xa8, 0x4e,
	0x84, 0x7e, 0x05, 0xe5, 0x3c, 0x7d, 0xcb, 0x6a, 0x63, 0x75, 0x75, 0xcb, 0xad, 0x83, 0x8a, 0x22,
	0x03, 0xd4, 0x21, 0xad, 0x50, 0x5f, 0xf4, 0xd8, 0xca, 0xad, 0x7a, 0x6c, 0x63, 0x28, 0x55, 0xf5,
	0xea, 0x86, 0xc9, 0x9b, 0xf5, 0xcf, 0x6d, 0x98, 0x6d, 0x50, 0xc3, 0x64, 0x72, 0x16, 0xa7, 0x17,
	0x01, 0x8b, 0x60, 0x8d, 0xe1, 0x68, 0x89, 0x86, 0xbe, 0x85, 0x4d, 0xea, 0xb4, 0xbf, 0xe4, 0xff,
	0xda, 0xad, 0xfc, 0xdf, 0xa0, 0xd2, 0x72, 0x67, 0xfa, 0x05, 0xb4, 0x52, 0x32, 0x1d, 0x07, 0x21,
	0x89, 0xfc, 0xe1, 0x15, 0x8d, 0x6f, 0x9d, 0xc5, 0x57, 0x2d, 0xa8, 0x47, 0x57, 0x4e, 0xd4, 0xfe,
	0x11, 0x60, 0x91, 0x1f, 0xd4, 0x02, 0xf0, 0xb0, 0xe1, 0xf6, 0x7d, 0xc7, 0x75, 0x3c, 0xed, 0x23,
	0xa4, 0x81, 0xca, 0xf7, 0xa7, 0xbd, 0x5e, 0xd7, 0xb6, 0x34, 0x05, 0x6d, 0x40, 0x83, 0x53, 0xbe,
	0x73, 0x5c, 0xdb, 0xd2, 0x4a, 0x0b, 0x91, 0xe3, 0x1e, 0x7e, 0x61, 0x5b, 0x5a, 0x19, 0xdd, 0x81,
	0x0d, 0x4e, 0x31, 0x7b, 0xee, 0xb1, 0x83, 0xbf, 0xb3, 0x2d, 0xad, 0x82, 0x10, 0xb4, 0x38, 0x11,
	0xdb, 0xa7, 0x5d, 0xc3, 0xb4, 0x2d, 0xad, 0xda, 0x1e, 0x40, 0x95, 0x43, 0x6b, 0x13, 0x9a, 0x7d,
	0xcf, 0xf0, 0x6c, 0x7f, 0xe0, 0xbe, 0x70, 0x7b, 0xaf, 0x5c, 0xed, 0xa3, 0x05, 0xe9, 0xd4, 0x76,
	0x2d, 0xc7, 0x3d, 0xd1, 0x14, 0x6a, 0x82, 0x93, 0x1c, 0xd7, 0x3f, 0xea, 0xf6, 0xcc, 0x17, 0x5a,
	0x69, 0x41, 0x9b, 0x9b, 0x2d, 0xb7, 0xff, 0x56, 0x82, 0x86, 0x94, 0x10, 0xd4, 0x82, 0x52, 0x9e,
	0x88, 0x12, 0x2c, 0xe5, 0xc9, 0xa2, 0x92, 0x4b, 0x72, 0x25, 0x3f, 0xe3, 0xbd, 0x68, 0x9a, 0xc6,
	0x21, 0x11, 0x68, 0xbb, 0xa1, 0xbb, 0xd1, 0xd6, 0x74, 0x4a, 0x45, 0x97, 0x7b, 0x58, 0xe5, 0x5a,
	0x0f, 0x3b, 0x84, 0xea, 0x65, 0x30, 0x9e, 0x11, 0x01, 0x9d, 0x1b, 0x0c, 0x72, 0x39, 0xea, 0x5b,
	0x3c, 0x99, 0xce, 0x8a, 0xfe, 0xcc, 0x37, 0x48, 0x05, 0xe5, 0x52, 0x34, 0x64, 0xe5, 0x92, 0xee,
	0x52, 0x96, 0x4b, 0x15, 0x2b, 0x29, 0xdd, 0x65, 0xac, 0xad, 0xaa, 0x58, 0xc9, 0xe6, 0xfd, 0xe8,
	0x9e, 0x74, 0x95, 0x21, 0xa8, 0x9c, 0xa5, 0xc9, 0x85, 0xbe, 0xc5, 0x69, 0x74, 0xdd, 0xfe, 0x67,
	0x65, 0xa9, 0x07, 0x31, 0x88, 0xfe, 0x5f, 0x05, 0x4a, 0xbe, 0x5d, 0x60, 0xf9, 0x76, 0x61, 0xa6,
	0x23, 0xf2, 0x56, 0xbf, 0x7b, 0xa0, 0x3c, 0x6e, 0x62, 0xbe, 0xb9, 0x6d, 0x64, 0xe9, 0x40, 0x90,
	0x92, 0x7c, 0x96, 0x4e, 0xf8, 0x15, 0x73, 0x9f, 0x0f, 0x04, 0x9c, 0xc4, 0xee, 0x98, 0x3d, 0x80,
	0xe9, 0x6c, 0x38, 0x8e, 0x43, 0xff, 0x35, 0xb9, 0xd2, 0x75, 0x7e, 0x05, 0x71, 0xca, 0x0b, 0x72,
	0x85, 0x0c, 0xa8, 0xd1, 0x76, 0x3d, 0xcb, 0xf4, 0xfd, 0xdb, 0xf4, 0x6b, 0x96, 0xb9, 0x3e, 0x53,
	0xc0, 0x42, 0x11, 0x7d, 0x03, 0x6b, 0xe2, 0x5e, 0xd7, 0x1f, 0xb2, 0x70, 0x7e, 0xf2, 0x81, 0xb6,
	0x29, 0x86, 0x80, 0x42, 0x0b, 0x7d, 0x01, 0xd5, 0x30, 0x18, 0x8f, 0x33, 0xfd, 0x80, 0xcd, 0x54,
	0xf7, 0x57, 0xa8, 0x9b, 0xc1, 0x78, 0x8c, 0xb9, 0x54, 0xfb, 0xef, 0x0a, 0xa0, 0x77, 0xcd, 0x5d,
	0x1b, 0x5f, 0x94, 0xeb, 0xe3, 0x4b, 0x07, 0xee, 0x84, 0xb3, 0x8b, 0xd9, 0x38, 0xc8, 0xe3, 0x4b,
	0xe2, 0xcf, 0x93, 0xc1, 0xb1, 0xb6, 0xb9, 0x60, 0x9d, 0x88, 0xb4, 0x2c, 0x8f, 0x27, 0xe5, 0xeb,
	0xe3, 0xc9, 0x13, 0xa8, 0xd0, 0x8d, 0x5e, 0x61, 0x2e, 0x6f, 0xad, 0x70, 0xb9, 0x9b, 0x8c, 0x30,
	0x93, 0x69, 0xff, 0x41, 0x81, 0x72, 0x37, 0x19, 0x21, 0x1d, 0xd6, 0x82, 0x28, 0x4a, 0x49, 0x56,
	0xdc, 0xd0, 0xc5, 0x96, 0x4e, 0x2c, 0x79, 0x32, 0x8d, 0xc3, 0x4c, 0x2f, 0xf1, 0xf9, 0x93, 0xef,
	0x68, 0xc6, 0x59, 0x5a, 0xf9, 0xf1, 0x6c, 0xbd, 0xc0, 0x4b, 0x45, 0xc6, 0xcb, 0x3e, 0x00, 0xeb,
	0xe2, 0x0e, 0x63, 0xd5, 0x18, 0x4b, 0xa2, 0xb4, 0xff, 0xb5, 0x0e, 0x15, 0x1a, 0xc4, 0x85, 0xba,
	0x22, 0xab, 0x3f, 0x02, 0x55, 0xcc, 0x95, 0x9c, 0x59, 0x62, 0x4c, 0x31, 0x6b, 0x32, 0x0b, 0x54,
	0x31, 0x22, 0xd3, 0xfc, 0x9c, 0x39, 0xd3, 0xc4, 0x7c, 0x43, 0x67, 0x23, 0x9a, 0x15, 0x3f, 0xbf,
	0x9a, 0xf2, 0x47, 0x47, 0xeb, 0xe9, 0xee, 0x7b, 0xf2, 0xe7, 0x5d, 0x4d, 0x09, 0xae, 0x87, 0x62,
	0x45, 0xbf, 0x99, 0xae, 0xc5, 0xab, 0x44, 0xc5, 0x62, 0x27, 0x47, 0xa9, 0xb6, 0x1c, 0xa5, 0x79,
	0xd5, 0xae, 0xdd, 0xb2, 0x6a, 0x97, 0x7a, 0x40, 0xfd, 0x5a, 0x0f, 0x78, 0x04, 0x2a, 0x65, 0x86,
	0xc9, 0x24, 0x9b, 0x5d, 0x90, 0x48, 0xcc, 0x8a, 0x8d, 0x51, 0x90, 0x99, 0x82, 0x74, 0xbd, 0xb8,
	0x9a, 0xef, 0x14, 0xd7, 0xbc, 0x2d, 0xb4, 0xe4, 0xb6, 0xf0, 0x31, 0x34, 0xc9, 0x5b, 0x12, 0xce,
	0x72, 0x12, 0xf9, 0xd4, 0x39, 0x36, 0xc3, 0xd5, 0xb1, 0x5a, 0x10, 0xcd, 0x24, 0x22, 0xf4, 0x33,
	0xb3, 0x59, 0x1c, 0xc6, 0x11, 0x61, 0xd3, 0x5c, 0x1d, 0x17, 0x5b, 0xf4, 0x0a, 0xb4, 0xd7, 0x24,
	0x0c, 0x83, 0xd7, 0xfe, 0x34, 0x25, 0xf1, 0x45, 0x40, 0xdf, 0x3a, 0x77, 0x19, 0xcc, 0x7e, 0xf9,
	0x9e, 0xc8, 0x76, 0x5e, 0x30, 0xf9, 0xd3, 0x42, 0xdc, 0x9e, 0xe4, 0xe9, 0x15, 0xde, 0x78, 0xbd,
	0x4c, 0xa5, 0x6f, 0xa8, 0x2c, 0x4f, 0xd2, 0x60, 0xb4, 0x78, 0x43, 0xdd, 0x7b, 0xef, 0x1b, 0xaa,
	0xcf, 0x25, 0x8b, 0x37, 0x54, 0x26, 0x6f, 0x57, 0x3e, 0xc7, 0xb6, 0x7e, 0xde, 0x73, 0x0c, 0x99,
	0xd0, 0x64, 0x9d, 0x7e, 0x6e, 0x48, 0x7f, 0xef, 0xcb, 0xca, 0x4d, 0x16, 0x66, 0xd4, 0x49, 0x22,
	0x19, 0x29, 0xca, 0x71, 0xfb, 0xc3, 0xe5, 0x88, 0x7e, 0x47, 0x27, 0xa3, 0x68, 0x71, 0xde, 0x0e,
	0xd3, 0xd9, 0x5b, 0x15, 0xdb, 0x24, 0x2a, 0x8e, 0x6b, 0x84, 0xf3, 0x75, 0x86, 0x3e, 0x03, 0x2d,
	0x4c, 0x49, 0x40, 0xf3, 0x1b, 0x84, 0x61, 0x32, 0x9b, 0xe4, 0x99, 0xbe, 0xcb, 0x0a, 0x77, 0x43,
	0xd0, 0x0d, 0x41, 0x46, 0xbf, 0x85, 0x06, 0x43, 0x99, 0x38, 0xeb, 0x01, 0x3b, 0xeb, 0xc1, 0x8a,
	0xb3, 0x4e, 0x82, 0x4c, 0x1c, 0x05, 0xa3, 0x62, 0x99, 0xa1, 0xaf, 0x80, 0xee, 0x7c, 0x72, 0x49,
	0xe8, 0x19, 0x7b, 0x4c, 0x7b, 0x77, 0xb5, 0xb6, 0x4d, 0x65, 0x30, 0x05, 0x3c, 0x5b, 0x65, 0x14,
	0x86, 0xbc, 0x43, 0xfb, 0x67, 0x41, 0x3c, 0x16, 0x17, 0x4f, 0x1d, 0xab, 0x9c, 0x78, 0xcc, 0x68,
	0xe8, 0x53, 0x8a, 0x09, 0x26, 0x94, 0x92, 0x4b, 0x92, 0xe6, 0x24, 0x62, 0x2f, 0x9c, 0x3a, 0xcd,
	0x38, 0xeb, 0xf2, 0x82, 0x4a, 0xe7, 0x67, 0x6a, 0x66, 0x96, 0x12, 0x3f, 0x25, 0x41, 0x96, 0x4c,
	0x8a, 0xf9, 0x59, 0x50, 0x31, 0x23, 0x52, 0x31, 0xd1, 0x85, 0x0b, 0x73, 0xfb, 0xcc, 0x5c, 0x93,
	0x77, 0x62, 0x41, 0xdc, 0x39, 0x82, 0xbb, 0xab, 0x30, 0x8b, 0x34, 0x28, 0xd3, 0x6b, 0x4a, 0x61,
	0xa6, 0xe9, 0x92, 0x96, 0x18, 0x2f, 0xfa, 0x12, 0xa3, 0xf1, 0xcd, 0x57, 0xa5, 0x2f, 0x95, 0xf6,
	0x0c, 0x9a, 0x4b, 0x20, 0xbd, 0xa1, 0xbf, 0x0a, 0xb3, 0xfc, 0x39, 0xcc, 0xcc, 0xee, 0xc2, 0x7a,
	0x32, 0x8e, 0x7c, 0x6e, 0x5a, 0xbc, 0x84, 0x93, 0x71, 0xf4, 0xb2, 0xe8, 0x1b, 0x13, 0xf2, 0x46,
	0x30, 0xf9, 0x43, 0xb8, 0x3e, 0x21, 0x6f, 0x18, 0xb3, 0xfd, 0x9f, 0x0a, 0x34, 0x97, 0x10, 0x7d,
	0xc3, 0xb9, 0xcf, 0xe4, 0x53, 0x4a, 0x1f, 0x1c, 0x5e, 0xe6, 0x0e, 0x3c, 0x93, 0x1d, 0xf8, 0xf0,
	0xd0, 0x53, 0xf8, 0x86, 0xbe, 0x81, 0x9a, 0x48, 0x0e, 0x6f, 0xc5, 0x9f, 0x7e, 0xa8, 0x1a, 0x3b,
	0x3c, 0x6d, 0x58, 0xa8, 0xb5, 0xff, 0x5c, 0x86, 0x9a, 0xc8, 0x24, 0x82, 0x16, 0xb6, 0x8d, 0x7e,
	0xcf, 0x95, 0xc6, 0xe4, 0x07, 0xa0, 0x0b, 0x1a, 0xb6, 0x5f, 0x19, 0xd8, 0x62, 0x63, 0xb9, 0x3f,
	0x70, 0xcd, 0xae, 0xad, 0x29, 0xef, 0xe1, 0x16, 0xb3, 0xf3, 0x3e, 0xec, 0x08, 0xae, 0x65, 0xf4,
	0x7c, 0x6c, 0x1f, 0x0f, 0x5c, 0x8b, 0xce, 0xec, 0x1e, 0x36, 0x4c, 0x4f, 0x2b, 0xa3, 0x3d, 0xd8,
	0x96, 0xf8, 0x86, 0xf5, 0xed, 0xa0, 0xef, 0xf9, 0x47, 0x46, 0xd7, 0x70, 0x4d, 0x5b, 0xab, 0xd0,
	0x31, 0x5f, 0xb0, 0xd9, 0x60, 0x7f, 0x6c, 0x63, 0xad, 0x8a, 0x76, 0x60, 0x4b, 0x10, 0x4f, 0x6c,
	0xd7, 0xee, 0x3b, 0xfd, 0xb9, 0x42, 0x4d, 0xf2, 0xff, 0xc4, 0xe8, 0xfb, 0x47, 0x83, 0x1f, 0xb4,
	0x35, 0xf4, 0x08, 0xf6, 0x96, 0x3d, 0x64, 0xb6, 0x0c, 0xd3, 0x73, 0x7a, 0xae, 0x7f, 0x6c, 0xdb,
	0x5a, 0x1d, 0xdd, 0x83, 0x4d, 0x49, 0x8d, 0xbb, 0xa9, 0xad, 0x23, 0x1d, 0xee, 0x16, 0xc7, 0xf7,
	0x06, 0xe6, 0x73, 0xdf, 0x30, 0xcd, 0xde, 0xc0, 0xf5, 0x34, 0x40, 0xdb, 0x70, 0x4f, 0x70, 0xfa,
	0x03, 0xc7, 0x74, 0x2c, 0xbb, 0x50, 0x6a, 0xa0, 0x5d, 0xb8, 0x7f, 0x8d, 0xf5, 0xca, 0xf1, 0x9e,
	0x5b, 0xd8, 0x78, 0xa5, 0x35, 0xd1, 0x01, 0x3c, 0x10, 0x4c, 0xd3, 0xe8, 0x76, 0x0b, 0xc7, 0xfd,
	0xde, 0x4b, 0x1b, 0x63, 0xc7, 0xb2, 0x35, 0xb5, 0x1d, 0x40, 0x43, 0xea, 0x78, 0x37, 0xc0, 0x6c,
	0xf7, 0x3a, 0xcc, 0x2a, 0xef, 0x03, 0x33, 0xff, 0xb1, 0x70, 0x01, 0xe6, 0xbf, 0x28, 0x00, 0x8b,
	0x2e, 0x77, 0xc3, 0x11, 0xdb, 0x40, 0x2d, 0xca, 0xbf, 0x2a, 0xad, 0x25, 0xe3, 0x88, 0xfd, 0x54,
	0x21, 0x58, 0xec, 0xa6, 0x2b, 0xcf, 0x59, 0xec, 0x92, 0xdb, 0x06, 0x7a, 0x14, 0xd7, 0xe2, 0x75,
	0xb4, 0x36, 0x21, 0x6f, 0x0a, 0x2d, 0xca, 0x62, 0x5a, 0xd5, 0x39, 0x8b, 0x6a, 0xb5, 0xff, 0x54,
	0x85, 0xf5, 0x79, 0x3b, 0x5c, 0xfe, 0x38, 0xe5, 0xa6, 0x8f, 0x2b, 0x2d, 0x7f, 0x1c, 0xfa, 0x7a,
	0x5e, 0x0d, 0x65, 0x56, 0x0d, 0x1f, 0xdf, 0xd4, 0x76, 0xaf, 0x57, 0xc2, 0x1f, 0x2b, 0x37, 0x56,
	0xc2, 0x06, 0x34, 0xa4, 0xec, 0x69, 0x0a, 0xba, 0x0b, 0x9a, 0x9c, 0x4e, 0xb3, 0x67, 0xd9, 0x5a,
	0x49, 0x02, 0x07, 0xa3, 0x5a, 0x86, 0x67, 0xf8, 0x66, 0xef, 0xf4, 0x07, 0xad, 0x2c, 0x2b, 0xf4,
	0x2c, 0x9b, 0x53, 0x2b, 0xe8, 0x3e, 0xdc, 0x91, 0xa9, 0x7d, 0xaf, 0x87, 0x8d, 0x13, 0x5b, 0xab,
	0x4a, 0xc5, 0x55, 0xd4, 0x8c, 0x6f, 0x62, 0xdb, 0xa0, 0xc8, 0xd5, 0x6a, 0x52, 0xf1, 0xbc, 0xc3,
	0x7d, 0xaa, 0xad, 0x49, 0xe8, 0xb5, 0xec, 0xae, 0x7d, 0x42, 0x5f, 0xb0, 0xcc, 0xed, 0xba, 0xe4,
	0x85, 0xfd, 0xd2, 0x76, 0x3d, 0xbf, 0xdb, 0x3b, 0x59, 0x42, 0xbb, 0xfd, 0xbd, 0x27, 0xf9, 0x07,
	0x12, 0xa4, 0x8f, 0x0d, 0xa7, 0x6b, 0x5b, 0xbe, 0xfd, 0xbd, 0x6d, 0x0e, 0x98, 0x17, 0x0d, 0x49,
	0xcd, 0x71, 0x3d, 0xec, 0xb8, 0x7d, 0xc7, 0xa4, 0x55, 0xa4, 0xa9, 0xe8, 0x21, 0xec, 0x0a, 0xce,
	0x29, 0xb6, 0xcd, 0xde, 0x77, 0xa7, 0x4c, 0x77, 0x5e, 0xfd, 0xcd, 0xa5, 0xca, 0x64, 0x9d, 0xc1,
	0x38, 0xf6, 0x6c, 0x2c, 0x59, 0x6f, 0xd1, 0x37, 0xfa, 0x5c, 0xc4, 0x1b, 0x60, 0x57, 0xdb, 0x90,
	0xbc, 0xe1, 0x24, 0x29, 0xc0, 0xda, 0x92, 0xfc, 0x4b, 0x1b, 0x7b, 0xda, 0xa6, 0xe4, 0x60, 0xdf,
	0xee, 0x1e, 0xfb, 0x96, 0xdd, 0xf7, 0xf0, 0xc0, 0xf4, 0x34, 0x84, 0xb6, 0x00, 0x15, 0x1c, 0xcf,
	0xf0, 0x1c, 0x93, 0xc7, 0xe7, 0x4e, 0xfb, 0x1f, 0x0a, 0xd4, 0x8b, 0xcb, 0x15, 0x75, 0xa0, 0x14,
	0x47, 0xe2, 0x97, 0xb2, 0xfd, 0x1b, 0x6e, 0xe1, 0x8e, 0x13, 0xe1, 0x52, 0x1c, 0xd1, 0x6b, 0x67,
	0x14, 0x64, 0x02, 0x97, 0x74, 0x89, 0x9e, 0xc0, 0xe6, 0x38, 0x9e, 0xbc, 0xa6, 0x83, 0x21, 0x9d,
	0x9a, 0xf9, 0xb0, 0xcd, 0x8b, 0x72, 0x83, 0x33, 0xe8, 0x3c, 0xc7, 0x47, 0xf6, 0xaf, 0xa1, 0xe4,
	0x44, 0xa8, 0x05, 0xe0, 0x58, 0xcb, 0xbf, 0x54, 0x38, 0x45, 0x74, 0x04, 0xf4, 0x10, 0xb4, 0x1c,
	0xcb, 0x3f, 0xb2, 0x8f, 0x7b, 0x58, 0xe4, 0xb5, 0xf4, 0xc4, 0x85, 0xad, 0xd5, 0xcf, 0x36, 0xd4,
	0x80, 0xb5, 0x85, 0xb5, 0x26, 0xac, 0xf7, 0x07, 0xa6, 0x69, 0xdb, 0x16, 0xfb, 0xb9, 0x05, 0xa0,
	0xc6, 0xd3, 0xaa, 0x95, 0x90, 0x0a, 0x75, 0x1e, 0x37, 0xdb, 0xd2, 0xca, 0x4f, 0x7e, 0x80, 0x7a,
	0x31, 0xc3, 0x53, 0xec, 0x0f, 0xdc, 0xfe, 0xa9, 0x6d, 0x3a, 0xc7, 0x8e, 0x6d, 0x69, 0x1f, 0xa1,
	0x3a, 0x54, 0x84, 0x2b, 0x2a, 0xd4, 0xe9, 0x4a, 0xa0, 0x5f, 0x85, 0x7a, 0x81, 0x37, 0xad, 0x4c,
	0x8d, 0xf3, 0xd8, 0x6a, 0x15, 0xba, 0x66, 0xf8, 0xb4, 0xb5, 0xea, 0xd1, 0x17, 0xbf, 0xff, 0x7c,
	0x14, 0xe7, 0xe7, 0xb3, 0x61, 0x27, 0x4c, 0x2e, 0x0e, 0x49, 0x92, 0x85, 0xc1, 0x24, 0x88, 0x82,
	0xc3, 0xe9, 0x70, 0x94, 0x1c, 0xbe, 0xf3, 0x8f, 0x96, 0x61, 0x8d, 0xfd, 0xe4, 0xfa, 0xeb, 0xff,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x27, 0xc4, 0x07, 0x84, 0x19, 0x00, 0x00,
}
