// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/merger/v1/merger.proto

package pbmerger

import (
	context "context"
	fmt "fmt"
	v1 "github.com/dfuse-io/pbgo/dfuse/bstream/v1"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	LowBlockNum          uint64   `protobuf:"varint,1,opt,name=lowBlockNum,proto3" json:"lowBlockNum,omitempty"`
	HighBlockID          string   `protobuf:"bytes,2,opt,name=highBlockID,proto3" json:"highBlockID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1327e68c6db98d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetLowBlockNum() uint64 {
	if m != nil {
		return m.LowBlockNum
	}
	return 0
}

func (m *Request) GetHighBlockID() string {
	if m != nil {
		return m.HighBlockID
	}
	return ""
}

type Response struct {
	Found                bool        `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Blocks               []*v1.Block `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1327e68c6db98d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *Response) GetBlocks() []*v1.Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "dfuse.merger.v1.Request")
	proto.RegisterType((*Response)(nil), "dfuse.merger.v1.Response")
}

func init() { proto.RegisterFile("dfuse/merger/v1/merger.proto", fileDescriptor_0f1327e68c6db98d) }

var fileDescriptor_0f1327e68c6db98d = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xd4, 0x3a, 0xb3, 0xc3, 0x20, 0x08, 0xd6, 0x21, 0x52, 0x76, 0xea, 0xc5, 0x84,
	0x6e, 0x47, 0x6f, 0x43, 0x04, 0x0f, 0x93, 0x99, 0xa3, 0x37, 0xb3, 0xbe, 0xb5, 0xc5, 0x75, 0xaf,
	0x26, 0x4d, 0xfd, 0xf7, 0xa5, 0x2f, 0x11, 0xc6, 0xd8, 0xed, 0x7d, 0x5f, 0x7e, 0x79, 0x7c, 0xdf,
	0x63, 0x0f, 0xc5, 0xce, 0x59, 0x90, 0x0d, 0x98, 0x12, 0x8c, 0xec, 0xf3, 0x30, 0x89, 0xd6, 0x60,
	0x87, 0x7c, 0x4a, 0xaf, 0x22, 0x78, 0x7d, 0x3e, 0x7b, 0xf4, 0xb8, 0xb6, 0x9d, 0x81, 0xaf, 0x66,
	0xe0, 0xc3, 0xe8, 0x3f, 0xcc, 0xd7, 0xec, 0x5a, 0xc1, 0x8f, 0x03, 0xdb, 0xf1, 0x94, 0x4d, 0xf6,
	0xf8, 0xbb, 0xda, 0xe3, 0xf6, 0xfb, 0xdd, 0x35, 0x49, 0x94, 0x46, 0xd9, 0xa5, 0x3a, 0xb6, 0x06,
	0xa2, 0xaa, 0xcb, 0x8a, 0xf4, 0xdb, 0x4b, 0x32, 0x4a, 0xa3, 0xec, 0x46, 0x1d, 0x5b, 0xf3, 0x0f,
	0x36, 0x56, 0x60, 0x5b, 0x3c, 0x58, 0xe0, 0xb7, 0xec, 0x6a, 0x87, 0xee, 0x50, 0xd0, 0xa6, 0xb1,
	0xf2, 0x82, 0x4b, 0x16, 0xeb, 0x01, 0xb6, 0xc9, 0x28, 0xbd, 0xc8, 0x26, 0x8b, 0x3b, 0xe1, 0x23,
	0xff, 0xc7, 0xea, 0x73, 0x41, 0xcb, 0x54, 0xc0, 0x16, 0x1b, 0x16, 0xaf, 0xa9, 0x0e, 0x7f, 0x65,
	0xd3, 0x8d, 0x01, 0x12, 0x05, 0x31, 0x96, 0x27, 0xe2, 0xa4, 0xb0, 0x08, 0x6d, 0x66, 0xf7, 0x67,
	0x5e, 0x7c, 0xb0, 0xd5, 0xf2, 0x33, 0x2f, 0xeb, 0xae, 0x72, 0x5a, 0x6c, 0xb1, 0x91, 0x84, 0x3d,
	0xd5, 0x28, 0x5b, 0x5d, 0xa2, 0x3c, 0xb9, 0xee, 0x73, 0xab, 0xfd, 0xac, 0x63, 0xba, 0xd7, 0xf2,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x28, 0x37, 0xaa, 0x80, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MergerClient is the client API for Merger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MergerClient interface {
	PreMergedBlocks(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type mergerClient struct {
	cc *grpc.ClientConn
}

func NewMergerClient(cc *grpc.ClientConn) MergerClient {
	return &mergerClient{cc}
}

func (c *mergerClient) PreMergedBlocks(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dfuse.merger.v1.Merger/PreMergedBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MergerServer is the server API for Merger service.
type MergerServer interface {
	PreMergedBlocks(context.Context, *Request) (*Response, error)
}

// UnimplementedMergerServer can be embedded to have forward compatible implementations.
type UnimplementedMergerServer struct {
}

func (*UnimplementedMergerServer) PreMergedBlocks(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreMergedBlocks not implemented")
}

func RegisterMergerServer(s *grpc.Server, srv MergerServer) {
	s.RegisterService(&_Merger_serviceDesc, srv)
}

func _Merger_PreMergedBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergerServer).PreMergedBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.merger.v1.Merger/PreMergedBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergerServer).PreMergedBlocks(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Merger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.merger.v1.Merger",
	HandlerType: (*MergerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreMergedBlocks",
			Handler:    _Merger_PreMergedBlocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfuse/merger/v1/merger.proto",
}
