// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/bstream/v1/bstream.proto

package pbbstream

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ForkStep int32

const (
	ForkStep_STEP_UNKNOWN      ForkStep = 0
	ForkStep_STEP_NEW          ForkStep = 1
	ForkStep_STEP_UNDO         ForkStep = 2
	ForkStep_STEP_REDO         ForkStep = 3
	ForkStep_STEP_IRREVERSIBLE ForkStep = 4
	ForkStep_STEP_STALLED      ForkStep = 5
)

var ForkStep_name = map[int32]string{
	0: "STEP_UNKNOWN",
	1: "STEP_NEW",
	2: "STEP_UNDO",
	3: "STEP_REDO",
	4: "STEP_IRREVERSIBLE",
	5: "STEP_STALLED",
}

var ForkStep_value = map[string]int32{
	"STEP_UNKNOWN":      0,
	"STEP_NEW":          1,
	"STEP_UNDO":         2,
	"STEP_REDO":         3,
	"STEP_IRREVERSIBLE": 4,
	"STEP_STALLED":      5,
}

func (x ForkStep) String() string {
	return proto.EnumName(ForkStep_name, int32(x))
}

func (ForkStep) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{0}
}

type Protocol int32

const (
	Protocol_UNKNOWN Protocol = 0
	Protocol_EOS     Protocol = 1
	Protocol_ETH     Protocol = 2
)

var Protocol_name = map[int32]string{
	0: "UNKNOWN",
	1: "EOS",
	2: "ETH",
}

var Protocol_value = map[string]int32{
	"UNKNOWN": 0,
	"EOS":     1,
	"ETH":     2,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}

func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{1}
}

// Whether we can assume the data will come ordered, unless there is a chain reorganization.
// mindreaders output ordered data, whereas relayers can output unordered data.
// The server can fail early if the assumption of the caller cannot be fulfilled.
type BlockRequest_Order int32

const (
	BlockRequest_UNSPECIFIED BlockRequest_Order = 0
	BlockRequest_ORDERED     BlockRequest_Order = 1
	BlockRequest_UNORDERED   BlockRequest_Order = 2
)

var BlockRequest_Order_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "ORDERED",
	2: "UNORDERED",
}

var BlockRequest_Order_value = map[string]int32{
	"UNSPECIFIED": 0,
	"ORDERED":     1,
	"UNORDERED":   2,
}

func (x BlockRequest_Order) String() string {
	return proto.EnumName(BlockRequest_Order_name, int32(x))
}

func (BlockRequest_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{0, 0}
}

type BlockRequest struct {
	// Number of blocks we want to get in burst upon connection, on a best effort basis.
	Burst int64 `protobuf:"varint,1,opt,name=burst,proto3" json:"burst,omitempty"`
	// Type of blocks we're after here, is it 'ethereum' data, 'eos', etc.. The server can fail early
	// if he doesn't match the data he serves (services mismatch, etc..)
	ContentType          string             `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Order                BlockRequest_Order `protobuf:"varint,3,opt,name=order,proto3,enum=dfuse.bstream.v1.BlockRequest_Order" json:"order,omitempty"`
	Requester            string             `protobuf:"bytes,4,opt,name=requester,proto3" json:"requester,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{0}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetBurst() int64 {
	if m != nil {
		return m.Burst
	}
	return 0
}

func (m *BlockRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *BlockRequest) GetOrder() BlockRequest_Order {
	if m != nil {
		return m.Order
	}
	return BlockRequest_UNSPECIFIED
}

func (m *BlockRequest) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

type BlocksRequestV2 struct {
	StartBlockNum        int64      `protobuf:"varint,1,opt,name=start_block_num,json=startBlockNum,proto3" json:"start_block_num,omitempty"`
	StartBlockId         uint64     `protobuf:"varint,2,opt,name=start_block_id,json=startBlockId,proto3" json:"start_block_id,omitempty"`
	ExcludeStartBlock    bool       `protobuf:"varint,3,opt,name=exclude_start_block,json=excludeStartBlock,proto3" json:"exclude_start_block,omitempty"`
	StreamBlocksFromLib  bool       `protobuf:"varint,4,opt,name=stream_blocks_from_lib,json=streamBlocksFromLib,proto3" json:"stream_blocks_from_lib,omitempty"`
	StopBlockNum         uint64     `protobuf:"varint,5,opt,name=stop_block_num,json=stopBlockNum,proto3" json:"stop_block_num,omitempty"`
	ExcludeStopBlock     bool       `protobuf:"varint,6,opt,name=exclude_stop_block,json=excludeStopBlock,proto3" json:"exclude_stop_block,omitempty"`
	HandleForks          bool       `protobuf:"varint,7,opt,name=handleForks,proto3" json:"handleForks,omitempty"`
	HandleForksSteps     []ForkStep `protobuf:"varint,8,rep,packed,name=handle_forks_steps,json=handleForksSteps,proto3,enum=dfuse.bstream.v1.ForkStep" json:"handle_forks_steps,omitempty"`
	Decoded              bool       `protobuf:"varint,9,opt,name=decoded,proto3" json:"decoded,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlocksRequestV2) Reset()         { *m = BlocksRequestV2{} }
func (m *BlocksRequestV2) String() string { return proto.CompactTextString(m) }
func (*BlocksRequestV2) ProtoMessage()    {}
func (*BlocksRequestV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{1}
}

func (m *BlocksRequestV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksRequestV2.Unmarshal(m, b)
}
func (m *BlocksRequestV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksRequestV2.Marshal(b, m, deterministic)
}
func (m *BlocksRequestV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksRequestV2.Merge(m, src)
}
func (m *BlocksRequestV2) XXX_Size() int {
	return xxx_messageInfo_BlocksRequestV2.Size(m)
}
func (m *BlocksRequestV2) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksRequestV2.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksRequestV2 proto.InternalMessageInfo

func (m *BlocksRequestV2) GetStartBlockNum() int64 {
	if m != nil {
		return m.StartBlockNum
	}
	return 0
}

func (m *BlocksRequestV2) GetStartBlockId() uint64 {
	if m != nil {
		return m.StartBlockId
	}
	return 0
}

func (m *BlocksRequestV2) GetExcludeStartBlock() bool {
	if m != nil {
		return m.ExcludeStartBlock
	}
	return false
}

func (m *BlocksRequestV2) GetStreamBlocksFromLib() bool {
	if m != nil {
		return m.StreamBlocksFromLib
	}
	return false
}

func (m *BlocksRequestV2) GetStopBlockNum() uint64 {
	if m != nil {
		return m.StopBlockNum
	}
	return 0
}

func (m *BlocksRequestV2) GetExcludeStopBlock() bool {
	if m != nil {
		return m.ExcludeStopBlock
	}
	return false
}

func (m *BlocksRequestV2) GetHandleForks() bool {
	if m != nil {
		return m.HandleForks
	}
	return false
}

func (m *BlocksRequestV2) GetHandleForksSteps() []ForkStep {
	if m != nil {
		return m.HandleForksSteps
	}
	return nil
}

func (m *BlocksRequestV2) GetDecoded() bool {
	if m != nil {
		return m.Decoded
	}
	return false
}

type BlockResponseV2 struct {
	// Chain specific blocks:
	// * dfuse.ethereum.codec.v1.Block
	// * dfuse.eosio.codec.v1.Block
	// Chain agnostic block, when request asks for packed blocks:
	// * dfuse.bstream.v1.Block
	Block                 *any.Any `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Undo                  bool     `protobuf:"varint,5,opt,name=undo,proto3" json:"undo,omitempty"`
	Step                  ForkStep `protobuf:"varint,6,opt,name=step,proto3,enum=dfuse.bstream.v1.ForkStep" json:"step,omitempty"`
	StepCount             uint64   `protobuf:"varint,7,opt,name=step_count,json=stepCount,proto3" json:"step_count,omitempty"`
	StepIndex             uint64   `protobuf:"varint,8,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	KnownToBeIrreversible bool     `protobuf:"varint,9,opt,name=known_to_be_irreversible,json=knownToBeIrreversible,proto3" json:"known_to_be_irreversible,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *BlockResponseV2) Reset()         { *m = BlockResponseV2{} }
func (m *BlockResponseV2) String() string { return proto.CompactTextString(m) }
func (*BlockResponseV2) ProtoMessage()    {}
func (*BlockResponseV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{2}
}

func (m *BlockResponseV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponseV2.Unmarshal(m, b)
}
func (m *BlockResponseV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponseV2.Marshal(b, m, deterministic)
}
func (m *BlockResponseV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponseV2.Merge(m, src)
}
func (m *BlockResponseV2) XXX_Size() int {
	return xxx_messageInfo_BlockResponseV2.Size(m)
}
func (m *BlockResponseV2) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponseV2.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponseV2 proto.InternalMessageInfo

func (m *BlockResponseV2) GetBlock() *any.Any {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockResponseV2) GetUndo() bool {
	if m != nil {
		return m.Undo
	}
	return false
}

func (m *BlockResponseV2) GetStep() ForkStep {
	if m != nil {
		return m.Step
	}
	return ForkStep_STEP_UNKNOWN
}

func (m *BlockResponseV2) GetStepCount() uint64 {
	if m != nil {
		return m.StepCount
	}
	return 0
}

func (m *BlockResponseV2) GetStepIndex() uint64 {
	if m != nil {
		return m.StepIndex
	}
	return 0
}

func (m *BlockResponseV2) GetKnownToBeIrreversible() bool {
	if m != nil {
		return m.KnownToBeIrreversible
	}
	return false
}

type Block struct {
	Number               uint64               `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PreviousId           string               `protobuf:"bytes,3,opt,name=previous_id,json=previousId,proto3" json:"previous_id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LibNum               uint64               `protobuf:"varint,5,opt,name=lib_num,json=libNum,proto3" json:"lib_num,omitempty"`
	PayloadKind          Protocol             `protobuf:"varint,6,opt,name=payload_kind,json=payloadKind,proto3,enum=dfuse.bstream.v1.Protocol" json:"payload_kind,omitempty"`
	PayloadVersion       int32                `protobuf:"varint,7,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	PayloadBuffer        []byte               `protobuf:"bytes,8,opt,name=payload_buffer,json=payloadBuffer,proto3" json:"payload_buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{3}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Block) GetPreviousId() string {
	if m != nil {
		return m.PreviousId
	}
	return ""
}

func (m *Block) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Block) GetLibNum() uint64 {
	if m != nil {
		return m.LibNum
	}
	return 0
}

func (m *Block) GetPayloadKind() Protocol {
	if m != nil {
		return m.PayloadKind
	}
	return Protocol_UNKNOWN
}

func (m *Block) GetPayloadVersion() int32 {
	if m != nil {
		return m.PayloadVersion
	}
	return 0
}

func (m *Block) GetPayloadBuffer() []byte {
	if m != nil {
		return m.PayloadBuffer
	}
	return nil
}

type BlockRef struct {
	Num                  uint64   `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRef) Reset()         { *m = BlockRef{} }
func (m *BlockRef) String() string { return proto.CompactTextString(m) }
func (*BlockRef) ProtoMessage()    {}
func (*BlockRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{4}
}

func (m *BlockRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRef.Unmarshal(m, b)
}
func (m *BlockRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRef.Marshal(b, m, deterministic)
}
func (m *BlockRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRef.Merge(m, src)
}
func (m *BlockRef) XXX_Size() int {
	return xxx_messageInfo_BlockRef.Size(m)
}
func (m *BlockRef) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRef.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRef proto.InternalMessageInfo

func (m *BlockRef) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *BlockRef) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TransactionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{5}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

type Transaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PayloadProtocol      Protocol `protobuf:"varint,6,opt,name=payload_protocol,json=payloadProtocol,proto3,enum=dfuse.bstream.v1.Protocol" json:"payload_protocol,omitempty"`
	PayloadBuffer        []byte   `protobuf:"bytes,8,opt,name=payload_buffer,json=payloadBuffer,proto3" json:"payload_buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfb17be2e7d1b7d, []int{6}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetPayloadProtocol() Protocol {
	if m != nil {
		return m.PayloadProtocol
	}
	return Protocol_UNKNOWN
}

func (m *Transaction) GetPayloadBuffer() []byte {
	if m != nil {
		return m.PayloadBuffer
	}
	return nil
}

func init() {
	proto.RegisterEnum("dfuse.bstream.v1.ForkStep", ForkStep_name, ForkStep_value)
	proto.RegisterEnum("dfuse.bstream.v1.Protocol", Protocol_name, Protocol_value)
	proto.RegisterEnum("dfuse.bstream.v1.BlockRequest_Order", BlockRequest_Order_name, BlockRequest_Order_value)
	proto.RegisterType((*BlockRequest)(nil), "dfuse.bstream.v1.BlockRequest")
	proto.RegisterType((*BlocksRequestV2)(nil), "dfuse.bstream.v1.BlocksRequestV2")
	proto.RegisterType((*BlockResponseV2)(nil), "dfuse.bstream.v1.BlockResponseV2")
	proto.RegisterType((*Block)(nil), "dfuse.bstream.v1.Block")
	proto.RegisterType((*BlockRef)(nil), "dfuse.bstream.v1.BlockRef")
	proto.RegisterType((*TransactionRequest)(nil), "dfuse.bstream.v1.TransactionRequest")
	proto.RegisterType((*Transaction)(nil), "dfuse.bstream.v1.Transaction")
}

func init() { proto.RegisterFile("dfuse/bstream/v1/bstream.proto", fileDescriptor_9cfb17be2e7d1b7d) }

var fileDescriptor_9cfb17be2e7d1b7d = []byte{
	// 963 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x0d, 0x75, 0xb1, 0xa4, 0xa1, 0x6c, 0x33, 0x13, 0x27, 0x61, 0x85, 0x26, 0x91, 0x85, 0xb4,
	0x75, 0x8d, 0x94, 0x72, 0xe8, 0x16, 0x2d, 0x5a, 0xf4, 0x21, 0xb2, 0x68, 0x44, 0x88, 0x21, 0x19,
	0x2b, 0x59, 0x01, 0xfa, 0x42, 0x90, 0xe2, 0xca, 0x61, 0x4d, 0x71, 0x19, 0x5e, 0xdc, 0xe8, 0x1b,
	0xfa, 0x0f, 0xfd, 0x88, 0xfe, 0x4c, 0x7f, 0xa5, 0x8f, 0x05, 0x97, 0x4b, 0x8a, 0xb0, 0x6b, 0x23,
	0x4f, 0xda, 0x39, 0x73, 0x66, 0xf7, 0x9c, 0xd9, 0xd1, 0x12, 0x9e, 0x3b, 0xcb, 0x24, 0xa2, 0x7d,
	0x3b, 0x8a, 0x43, 0x6a, 0xad, 0xfa, 0xd7, 0xaf, 0xf3, 0xa5, 0x16, 0x84, 0x2c, 0x66, 0xa8, 0xf0,
	0xbc, 0x96, 0x83, 0xd7, 0xaf, 0x3b, 0x2f, 0x2e, 0x19, 0xbb, 0xf4, 0x68, 0x9f, 0xe7, 0xed, 0x64,
	0xd9, 0x8f, 0xdd, 0x15, 0x8d, 0x62, 0x6b, 0x15, 0x64, 0x25, 0x9d, 0x2f, 0x6e, 0x12, 0x2c, 0x7f,
	0x9d, 0xa5, 0x7a, 0xff, 0x48, 0xd0, 0x1e, 0x78, 0x6c, 0x71, 0x45, 0xe8, 0xc7, 0x84, 0x46, 0x31,
	0xee, 0x41, 0xdd, 0x4e, 0xc2, 0x28, 0x56, 0xa5, 0xae, 0x74, 0x50, 0x25, 0x59, 0x80, 0xfb, 0xd0,
	0x5e, 0x30, 0x3f, 0xa6, 0x7e, 0x6c, 0xc6, 0xeb, 0x80, 0xaa, 0x95, 0xae, 0x74, 0xd0, 0x22, 0xb2,
	0xc0, 0x66, 0xeb, 0x80, 0xe2, 0xcf, 0x50, 0x67, 0xa1, 0x43, 0x43, 0xb5, 0xda, 0x95, 0x0e, 0x76,
	0xf4, 0x97, 0xda, 0x4d, 0x9d, 0x5a, 0xf9, 0x1c, 0x6d, 0x92, 0x72, 0x49, 0x56, 0x82, 0x5f, 0x42,
	0x2b, 0xcc, 0x70, 0x1a, 0xaa, 0x35, 0xbe, 0xf7, 0x06, 0xe8, 0x7d, 0x0f, 0x75, 0xce, 0xc6, 0x5d,
	0x90, 0x2f, 0xc6, 0xd3, 0x73, 0xe3, 0x64, 0x74, 0x3a, 0x32, 0x86, 0xca, 0x03, 0x94, 0xa1, 0x31,
	0x21, 0x43, 0x83, 0x18, 0x43, 0x45, 0xc2, 0x6d, 0x68, 0x5d, 0x8c, 0xf3, 0xb0, 0xd2, 0xfb, 0xab,
	0x0a, 0xbb, 0xfc, 0xc4, 0x48, 0x1c, 0x39, 0xd7, 0xf1, 0x6b, 0xd8, 0x8d, 0x62, 0x2b, 0x8c, 0x4d,
	0x3b, 0x4d, 0x98, 0x7e, 0xb2, 0x12, 0x36, 0xb7, 0x39, 0xcc, 0xe9, 0xe3, 0x64, 0x85, 0x2f, 0x61,
	0xa7, 0xcc, 0x73, 0x1d, 0x6e, 0xb8, 0x46, 0xda, 0x1b, 0xda, 0xc8, 0x41, 0x0d, 0x1e, 0xd1, 0x4f,
	0x0b, 0x2f, 0x71, 0xa8, 0x59, 0x62, 0x73, 0xff, 0x4d, 0xf2, 0x50, 0xa4, 0xa6, 0x45, 0x05, 0x1e,
	0xc3, 0x93, 0xac, 0x19, 0x19, 0x31, 0x32, 0x97, 0x21, 0x5b, 0x99, 0x9e, 0x6b, 0x73, 0xcb, 0x4d,
	0xf2, 0x28, 0xcb, 0x66, 0xa2, 0x4f, 0x43, 0xb6, 0x3a, 0x73, 0xed, 0x4c, 0x0a, 0x0b, 0x4a, 0x8a,
	0xeb, 0xb9, 0x14, 0x16, 0x14, 0x82, 0x5f, 0x01, 0x6e, 0xa4, 0xe4, 0x6c, 0x75, 0x8b, 0x6f, 0xab,
	0x14, 0x4a, 0x44, 0x01, 0x76, 0x41, 0xfe, 0x60, 0xf9, 0x8e, 0x47, 0x4f, 0x59, 0x78, 0x15, 0xa9,
	0x0d, 0x4e, 0x2b, 0x43, 0xf8, 0x16, 0x30, 0x0b, 0xcd, 0x65, 0x1a, 0x9b, 0x51, 0x4c, 0x83, 0x48,
	0x6d, 0x76, 0xab, 0x07, 0x3b, 0x7a, 0xe7, 0xf6, 0xcd, 0xa6, 0x45, 0xd3, 0x98, 0x06, 0x44, 0x29,
	0x6d, 0x92, 0x02, 0x11, 0xaa, 0xd0, 0x70, 0xe8, 0x82, 0x39, 0xd4, 0x51, 0x5b, 0xfc, 0x9c, 0x3c,
	0xec, 0xfd, 0x2b, 0x89, 0x0b, 0x22, 0x34, 0x0a, 0x98, 0x1f, 0xd1, 0xb9, 0x8e, 0x87, 0x50, 0xcf,
	0xa4, 0xa7, 0xd7, 0x22, 0xeb, 0x7b, 0x5a, 0x36, 0xb9, 0x5a, 0x3e, 0xb9, 0xda, 0x1b, 0x7f, 0x4d,
	0x32, 0x0a, 0x22, 0xd4, 0x12, 0xdf, 0x61, 0xbc, 0x1f, 0x4d, 0xc2, 0xd7, 0xa8, 0x41, 0x2d, 0x95,
	0xca, 0x9d, 0xdf, 0xaf, 0x94, 0xf3, 0xf0, 0x19, 0x40, 0xfa, 0x6b, 0x2e, 0x58, 0xe2, 0xc7, 0xbc,
	0x11, 0x35, 0xd2, 0x4a, 0x91, 0x93, 0x14, 0x28, 0xd2, 0xae, 0xef, 0xd0, 0x4f, 0x6a, 0x73, 0x93,
	0x1e, 0xa5, 0x00, 0xfe, 0x08, 0xea, 0x95, 0xcf, 0xfe, 0xf0, 0xcd, 0x98, 0x99, 0x36, 0x35, 0xdd,
	0x30, 0xa4, 0xd7, 0x34, 0x8c, 0x5c, 0xdb, 0xa3, 0xc2, 0xec, 0x63, 0x9e, 0x9f, 0xb1, 0x01, 0x1d,
	0x95, 0x92, 0xbd, 0xbf, 0x2b, 0x50, 0xcf, 0xae, 0xe2, 0x09, 0x6c, 0xf9, 0xc9, 0xca, 0xa6, 0x21,
	0x77, 0x5c, 0x23, 0x22, 0xc2, 0x1d, 0xa8, 0x88, 0xa9, 0x6b, 0x91, 0x8a, 0xeb, 0xe0, 0x0b, 0x90,
	0x83, 0x90, 0x5e, 0xbb, 0x2c, 0x89, 0xd2, 0x71, 0xac, 0xf2, 0x04, 0xe4, 0xd0, 0xc8, 0xc1, 0x9f,
	0xa0, 0x55, 0xfc, 0xed, 0xf9, 0x3c, 0xc9, 0x7a, 0xe7, 0x56, 0xf7, 0x66, 0x39, 0x83, 0x6c, 0xc8,
	0xf8, 0x14, 0x1a, 0x9e, 0x6b, 0x97, 0x46, 0x6b, 0xcb, 0x73, 0xed, 0x74, 0xa8, 0x7e, 0x85, 0x76,
	0x60, 0xad, 0x3d, 0x66, 0x39, 0xe6, 0x95, 0xeb, 0x3b, 0x77, 0x37, 0xf5, 0x3c, 0xdd, 0x7f, 0xc1,
	0x3c, 0x22, 0x0b, 0xfe, 0x3b, 0xd7, 0x77, 0xf0, 0x1b, 0xd8, 0xcd, 0xcb, 0xb9, 0x71, 0xe6, 0xf3,
	0x06, 0xd7, 0xc9, 0x8e, 0x80, 0xe7, 0x19, 0x8a, 0x5f, 0x41, 0x8e, 0x98, 0x76, 0xb2, 0x5c, 0xd2,
	0x90, 0x77, 0xba, 0x4d, 0xb6, 0x05, 0x3a, 0xe0, 0x60, 0xef, 0x15, 0x34, 0xc5, 0xb8, 0x2c, 0x51,
	0x81, 0x6a, 0xfe, 0xe7, 0xad, 0x91, 0x74, 0x79, 0xb3, 0x61, 0xbd, 0x3d, 0xc0, 0x59, 0x68, 0xf9,
	0x91, 0xb5, 0x88, 0x5d, 0xe6, 0x8b, 0x27, 0xa0, 0xf7, 0xa7, 0x04, 0x72, 0x09, 0x16, 0x55, 0x52,
	0xd1, 0x66, 0x03, 0x94, 0x5c, 0x4a, 0x20, 0x4c, 0x7d, 0x86, 0xed, 0xdc, 0x67, 0x0e, 0x7c, 0xa6,
	0xa3, 0xc3, 0x8f, 0xd0, 0xcc, 0xe7, 0x11, 0x15, 0x68, 0x4f, 0x67, 0xc6, 0xb9, 0x79, 0x31, 0x7e,
	0x37, 0x9e, 0xbc, 0x1f, 0x2b, 0x0f, 0xb0, 0x0d, 0x4d, 0x8e, 0x8c, 0x8d, 0xf7, 0xd9, 0xeb, 0x26,
	0xf2, 0xc3, 0x89, 0x52, 0x29, 0x42, 0x62, 0x0c, 0x27, 0x4a, 0x15, 0x1f, 0xc3, 0x43, 0x1e, 0x8e,
	0x08, 0x31, 0xe6, 0x06, 0x99, 0x8e, 0x06, 0x67, 0x86, 0x52, 0x2b, 0x36, 0x9d, 0xce, 0xde, 0x9c,
	0x9d, 0x19, 0x43, 0xa5, 0x7e, 0xf8, 0x2d, 0x34, 0x0b, 0x95, 0x32, 0x34, 0x36, 0xa7, 0x35, 0xa0,
	0x6a, 0x4c, 0xa6, 0x8a, 0xc4, 0x17, 0xb3, 0xb7, 0x4a, 0x45, 0x27, 0x20, 0xf3, 0x7e, 0x4f, 0xb9,
	0x61, 0x3c, 0x81, 0xad, 0xec, 0x65, 0xc2, 0xe7, 0xf7, 0x3f, 0xed, 0x9d, 0xa7, 0x77, 0xe4, 0x8f,
	0x24, 0xdd, 0x82, 0xed, 0xd2, 0x9e, 0x73, 0x1d, 0xcf, 0x8b, 0x5d, 0xf7, 0xef, 0xa8, 0xda, 0x3c,
	0xdf, 0x9d, 0xfd, 0x3b, 0x0f, 0xce, 0x1f, 0x90, 0x23, 0x49, 0xff, 0x1d, 0x1e, 0x96, 0x6e, 0x58,
	0x88, 0xbf, 0x80, 0x76, 0x09, 0x8c, 0xf0, 0x7f, 0xbe, 0x4e, 0xb7, 0xa7, 0xa5, 0xf3, 0xec, 0x5e,
	0xd6, 0x91, 0x34, 0xf8, 0xe1, 0xb7, 0xe3, 0x4b, 0x37, 0xfe, 0x90, 0xd8, 0xda, 0x82, 0xad, 0xfa,
	0x9c, 0xfc, 0x9d, 0xcb, 0xfa, 0x81, 0x7d, 0xc9, 0xfa, 0x37, 0x3f, 0xe3, 0xbf, 0x04, 0xb6, 0x08,
	0xec, 0x2d, 0x3e, 0x5b, 0xc7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x40, 0xc4, 0x61, 0x1a, 0xeb,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockStreamClient is the client API for BlockStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockStreamClient interface {
	Blocks(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (BlockStream_BlocksClient, error)
}

type blockStreamClient struct {
	cc *grpc.ClientConn
}

func NewBlockStreamClient(cc *grpc.ClientConn) BlockStreamClient {
	return &blockStreamClient{cc}
}

func (c *blockStreamClient) Blocks(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (BlockStream_BlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BlockStream_serviceDesc.Streams[0], "/dfuse.bstream.v1.BlockStream/Blocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &blockStreamBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlockStream_BlocksClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type blockStreamBlocksClient struct {
	grpc.ClientStream
}

func (x *blockStreamBlocksClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlockStreamServer is the server API for BlockStream service.
type BlockStreamServer interface {
	Blocks(*BlockRequest, BlockStream_BlocksServer) error
}

// UnimplementedBlockStreamServer can be embedded to have forward compatible implementations.
type UnimplementedBlockStreamServer struct {
}

func (*UnimplementedBlockStreamServer) Blocks(req *BlockRequest, srv BlockStream_BlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method Blocks not implemented")
}

func RegisterBlockStreamServer(s *grpc.Server, srv BlockStreamServer) {
	s.RegisterService(&_BlockStream_serviceDesc, srv)
}

func _BlockStream_Blocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockStreamServer).Blocks(m, &blockStreamBlocksServer{stream})
}

type BlockStream_BlocksServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type blockStreamBlocksServer struct {
	grpc.ServerStream
}

func (x *blockStreamBlocksServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

var _BlockStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.bstream.v1.BlockStream",
	HandlerType: (*BlockStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Blocks",
			Handler:       _BlockStream_Blocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/bstream/v1/bstream.proto",
}

// BlockStreamV2Client is the client API for BlockStreamV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockStreamV2Client interface {
	Blocks(ctx context.Context, in *BlocksRequestV2, opts ...grpc.CallOption) (BlockStreamV2_BlocksClient, error)
}

type blockStreamV2Client struct {
	cc *grpc.ClientConn
}

func NewBlockStreamV2Client(cc *grpc.ClientConn) BlockStreamV2Client {
	return &blockStreamV2Client{cc}
}

func (c *blockStreamV2Client) Blocks(ctx context.Context, in *BlocksRequestV2, opts ...grpc.CallOption) (BlockStreamV2_BlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BlockStreamV2_serviceDesc.Streams[0], "/dfuse.bstream.v1.BlockStreamV2/Blocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &blockStreamV2BlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlockStreamV2_BlocksClient interface {
	Recv() (*BlockResponseV2, error)
	grpc.ClientStream
}

type blockStreamV2BlocksClient struct {
	grpc.ClientStream
}

func (x *blockStreamV2BlocksClient) Recv() (*BlockResponseV2, error) {
	m := new(BlockResponseV2)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlockStreamV2Server is the server API for BlockStreamV2 service.
type BlockStreamV2Server interface {
	Blocks(*BlocksRequestV2, BlockStreamV2_BlocksServer) error
}

// UnimplementedBlockStreamV2Server can be embedded to have forward compatible implementations.
type UnimplementedBlockStreamV2Server struct {
}

func (*UnimplementedBlockStreamV2Server) Blocks(req *BlocksRequestV2, srv BlockStreamV2_BlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method Blocks not implemented")
}

func RegisterBlockStreamV2Server(s *grpc.Server, srv BlockStreamV2Server) {
	s.RegisterService(&_BlockStreamV2_serviceDesc, srv)
}

func _BlockStreamV2_Blocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlocksRequestV2)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockStreamV2Server).Blocks(m, &blockStreamV2BlocksServer{stream})
}

type BlockStreamV2_BlocksServer interface {
	Send(*BlockResponseV2) error
	grpc.ServerStream
}

type blockStreamV2BlocksServer struct {
	grpc.ServerStream
}

func (x *blockStreamV2BlocksServer) Send(m *BlockResponseV2) error {
	return x.ServerStream.SendMsg(m)
}

var _BlockStreamV2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.bstream.v1.BlockStreamV2",
	HandlerType: (*BlockStreamV2Server)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Blocks",
			Handler:       _BlockStreamV2_Blocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/bstream/v1/bstream.proto",
}

// TransactionStreamClient is the client API for TransactionStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionStreamClient interface {
	Transactions(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (TransactionStream_TransactionsClient, error)
}

type transactionStreamClient struct {
	cc *grpc.ClientConn
}

func NewTransactionStreamClient(cc *grpc.ClientConn) TransactionStreamClient {
	return &transactionStreamClient{cc}
}

func (c *transactionStreamClient) Transactions(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (TransactionStream_TransactionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TransactionStream_serviceDesc.Streams[0], "/dfuse.bstream.v1.TransactionStream/Transactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionStreamTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactionStream_TransactionsClient interface {
	Recv() (*Transaction, error)
	grpc.ClientStream
}

type transactionStreamTransactionsClient struct {
	grpc.ClientStream
}

func (x *transactionStreamTransactionsClient) Recv() (*Transaction, error) {
	m := new(Transaction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactionStreamServer is the server API for TransactionStream service.
type TransactionStreamServer interface {
	Transactions(*TransactionRequest, TransactionStream_TransactionsServer) error
}

// UnimplementedTransactionStreamServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionStreamServer struct {
}

func (*UnimplementedTransactionStreamServer) Transactions(req *TransactionRequest, srv TransactionStream_TransactionsServer) error {
	return status.Errorf(codes.Unimplemented, "method Transactions not implemented")
}

func RegisterTransactionStreamServer(s *grpc.Server, srv TransactionStreamServer) {
	s.RegisterService(&_TransactionStream_serviceDesc, srv)
}

func _TransactionStream_Transactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransactionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionStreamServer).Transactions(m, &transactionStreamTransactionsServer{stream})
}

type TransactionStream_TransactionsServer interface {
	Send(*Transaction) error
	grpc.ServerStream
}

type transactionStreamTransactionsServer struct {
	grpc.ServerStream
}

func (x *transactionStreamTransactionsServer) Send(m *Transaction) error {
	return x.ServerStream.SendMsg(m)
}

var _TransactionStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.bstream.v1.TransactionStream",
	HandlerType: (*TransactionStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transactions",
			Handler:       _TransactionStream_Transactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/bstream/v1/bstream.proto",
}
