// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sf/graphql/v1/graphql.proto

package pbgraphql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Variables     *structpb.Struct       `protobuf:"bytes,2,opt,name=variables,proto3" json:"variables,omitempty"`
	OperationName string                 `protobuf:"bytes,3,opt,name=operationName,proto3" json:"operationName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_sf_graphql_v1_graphql_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Request) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Request) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Errors        []*Error               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_sf_graphql_v1_graphql_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Response) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

// GraphQL Error
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description of the error intended for the developer.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The source location for the error.
	Locations []*SourceLocation `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	// Path to the `null` value justified by this error.
	Path *structpb.ListValue `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Free-form extensions (starts with a map)
	Extensions    *structpb.Struct `protobuf:"bytes,4,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_sf_graphql_v1_graphql_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetLocations() []*SourceLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *Error) GetPath() *structpb.ListValue {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Error) GetExtensions() *structpb.Struct {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// The source location of an error.
type SourceLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The line the error occurred at.
	Line int32 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	// The column the error occurred at.
	Column        int32 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceLocation) Reset() {
	*x = SourceLocation{}
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceLocation) ProtoMessage() {}

func (x *SourceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceLocation.ProtoReflect.Descriptor instead.
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return file_sf_graphql_v1_graphql_proto_rawDescGZIP(), []int{3}
}

func (x *SourceLocation) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *SourceLocation) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type BlockCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ver           int32                  `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	BlockNum      uint64                 `protobuf:"varint,2,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	BlockId       string                 `protobuf:"bytes,3,opt,name=blockId,proto3" json:"blockId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCursor) Reset() {
	*x = BlockCursor{}
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCursor) ProtoMessage() {}

func (x *BlockCursor) ProtoReflect() protoreflect.Message {
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCursor.ProtoReflect.Descriptor instead.
func (*BlockCursor) Descriptor() ([]byte, []int) {
	return file_sf_graphql_v1_graphql_proto_rawDescGZIP(), []int{4}
}

func (x *BlockCursor) GetVer() int32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *BlockCursor) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *BlockCursor) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

type TransactionCursor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ver              int32                  `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,2,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	TransactionHash  string                 `protobuf:"bytes,3,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionCursor) Reset() {
	*x = TransactionCursor{}
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCursor) ProtoMessage() {}

func (x *TransactionCursor) ProtoReflect() protoreflect.Message {
	mi := &file_sf_graphql_v1_graphql_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCursor.ProtoReflect.Descriptor instead.
func (*TransactionCursor) Descriptor() ([]byte, []int) {
	return file_sf_graphql_v1_graphql_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionCursor) GetVer() int32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *TransactionCursor) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *TransactionCursor) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

var File_sf_graphql_v1_graphql_proto protoreflect.FileDescriptor

const file_sf_graphql_v1_graphql_proto_rawDesc = "" +
	"\n" +
	"\x1bsf/graphql/v1/graphql.proto\x12\rsf.graphql.v1\x1a\x1cgoogle/protobuf/struct.proto\"|\n" +
	"\aRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x125\n" +
	"\tvariables\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tvariables\x12$\n" +
	"\roperationName\x18\x03 \x01(\tR\roperationName\"L\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.sf.graphql.v1.ErrorR\x06errors\"\xc7\x01\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12;\n" +
	"\tlocations\x18\x02 \x03(\v2\x1d.sf.graphql.v1.SourceLocationR\tlocations\x12.\n" +
	"\x04path\x18\x03 \x01(\v2\x1a.google.protobuf.ListValueR\x04path\x127\n" +
	"\n" +
	"extensions\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"extensions\"<\n" +
	"\x0eSourceLocation\x12\x12\n" +
	"\x04line\x18\x01 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x05R\x06column\"U\n" +
	"\vBlockCursor\x12\x10\n" +
	"\x03ver\x18\x01 \x01(\x05R\x03ver\x12\x1a\n" +
	"\bblockNum\x18\x02 \x01(\x04R\bblockNum\x12\x18\n" +
	"\ablockId\x18\x03 \x01(\tR\ablockId\"{\n" +
	"\x11TransactionCursor\x12\x10\n" +
	"\x03ver\x18\x01 \x01(\x05R\x03ver\x12*\n" +
	"\x10transactionIndex\x18\x02 \x01(\rR\x10transactionIndex\x12(\n" +
	"\x0ftransactionHash\x18\x03 \x01(\tR\x0ftransactionHash2I\n" +
	"\aGraphQL\x12>\n" +
	"\aExecute\x12\x16.sf.graphql.v1.Request\x1a\x17.sf.graphql.v1.Response\"\x000\x01B7Z5github.com/streamingfast/pbgo/sf/graphql/v1;pbgraphqlb\x06proto3"

var (
	file_sf_graphql_v1_graphql_proto_rawDescOnce sync.Once
	file_sf_graphql_v1_graphql_proto_rawDescData []byte
)

func file_sf_graphql_v1_graphql_proto_rawDescGZIP() []byte {
	file_sf_graphql_v1_graphql_proto_rawDescOnce.Do(func() {
		file_sf_graphql_v1_graphql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_graphql_v1_graphql_proto_rawDesc), len(file_sf_graphql_v1_graphql_proto_rawDesc)))
	})
	return file_sf_graphql_v1_graphql_proto_rawDescData
}

var file_sf_graphql_v1_graphql_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sf_graphql_v1_graphql_proto_goTypes = []any{
	(*Request)(nil),            // 0: sf.graphql.v1.Request
	(*Response)(nil),           // 1: sf.graphql.v1.Response
	(*Error)(nil),              // 2: sf.graphql.v1.Error
	(*SourceLocation)(nil),     // 3: sf.graphql.v1.SourceLocation
	(*BlockCursor)(nil),        // 4: sf.graphql.v1.BlockCursor
	(*TransactionCursor)(nil),  // 5: sf.graphql.v1.TransactionCursor
	(*structpb.Struct)(nil),    // 6: google.protobuf.Struct
	(*structpb.ListValue)(nil), // 7: google.protobuf.ListValue
}
var file_sf_graphql_v1_graphql_proto_depIdxs = []int32{
	6, // 0: sf.graphql.v1.Request.variables:type_name -> google.protobuf.Struct
	2, // 1: sf.graphql.v1.Response.errors:type_name -> sf.graphql.v1.Error
	3, // 2: sf.graphql.v1.Error.locations:type_name -> sf.graphql.v1.SourceLocation
	7, // 3: sf.graphql.v1.Error.path:type_name -> google.protobuf.ListValue
	6, // 4: sf.graphql.v1.Error.extensions:type_name -> google.protobuf.Struct
	0, // 5: sf.graphql.v1.GraphQL.Execute:input_type -> sf.graphql.v1.Request
	1, // 6: sf.graphql.v1.GraphQL.Execute:output_type -> sf.graphql.v1.Response
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sf_graphql_v1_graphql_proto_init() }
func file_sf_graphql_v1_graphql_proto_init() {
	if File_sf_graphql_v1_graphql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_graphql_v1_graphql_proto_rawDesc), len(file_sf_graphql_v1_graphql_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_graphql_v1_graphql_proto_goTypes,
		DependencyIndexes: file_sf_graphql_v1_graphql_proto_depIdxs,
		MessageInfos:      file_sf_graphql_v1_graphql_proto_msgTypes,
	}.Build()
	File_sf_graphql_v1_graphql_proto = out.File
	file_sf_graphql_v1_graphql_proto_goTypes = nil
	file_sf_graphql_v1_graphql_proto_depIdxs = nil
}
