// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: sf/graphql/v1/graphql.proto

package pbgraphql

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphQL_Execute_FullMethodName = "/sf.graphql.v1.GraphQL/Execute"
)

// GraphQLClient is the client API for GraphQL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraphQLClient interface {
	Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
}

type graphQLClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphQLClient(cc grpc.ClientConnInterface) GraphQLClient {
	return &graphQLClient{cc}
}

func (c *graphQLClient) Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GraphQL_ServiceDesc.Streams[0], GraphQL_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphQL_ExecuteClient = grpc.ServerStreamingClient[Response]

// GraphQLServer is the server API for GraphQL service.
// All implementations should embed UnimplementedGraphQLServer
// for forward compatibility.
type GraphQLServer interface {
	Execute(*Request, grpc.ServerStreamingServer[Response]) error
}

// UnimplementedGraphQLServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphQLServer struct{}

func (UnimplementedGraphQLServer) Execute(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedGraphQLServer) testEmbeddedByValue() {}

// UnsafeGraphQLServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphQLServer will
// result in compilation errors.
type UnsafeGraphQLServer interface {
	mustEmbedUnimplementedGraphQLServer()
}

func RegisterGraphQLServer(s grpc.ServiceRegistrar, srv GraphQLServer) {
	// If the following call pancis, it indicates UnimplementedGraphQLServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphQL_ServiceDesc, srv)
}

func _GraphQL_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraphQLServer).Execute(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphQL_ExecuteServer = grpc.ServerStreamingServer[Response]

// GraphQL_ServiceDesc is the grpc.ServiceDesc for GraphQL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphQL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.graphql.v1.GraphQL",
	HandlerType: (*GraphQLServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _GraphQL_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sf/graphql/v1/graphql.proto",
}
