// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/fluxdb/v1/fluxdb.proto

package pbfluxdb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Index struct {
	SquelchedCount       uint64            `protobuf:"varint,1,opt,name=squelched_count,json=squelchedCount,proto3" json:"squelched_count,omitempty"`
	PrimaryKeyToHeight   map[string]uint32 `protobuf:"bytes,2,rep,name=primary_key_to_height,json=primaryKeyToHeight,proto3" json:"primary_key_to_height,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_74afbad2e99b142c, []int{0}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetSquelchedCount() uint64 {
	if m != nil {
		return m.SquelchedCount
	}
	return 0
}

func (m *Index) GetPrimaryKeyToHeight() map[string]uint32 {
	if m != nil {
		return m.PrimaryKeyToHeight
	}
	return nil
}

// Row represents a FluxDB storage row as seen by the underlying storage
// engine which is a Key-Value store.
//
// A FluxDB row is always of the form:
// ```
// <collection>/<tablet>/<height>/<primaryKey> => <payload>
// ```
type Row struct {
	Collection           string   `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	TabletKey            string   `protobuf:"bytes,2,opt,name=tablet_key,json=tabletKey,proto3" json:"tablet_key,omitempty"`
	HeightKey            string   `protobuf:"bytes,3,opt,name=height_key,json=heightKey,proto3" json:"height_key,omitempty"`
	PrimKey              string   `protobuf:"bytes,4,opt,name=prim_key,json=primKey,proto3" json:"prim_key,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_74afbad2e99b142c, []int{1}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *Row) GetTabletKey() string {
	if m != nil {
		return m.TabletKey
	}
	return ""
}

func (m *Row) GetHeightKey() string {
	if m != nil {
		return m.HeightKey
	}
	return ""
}

func (m *Row) GetPrimKey() string {
	if m != nil {
		return m.PrimKey
	}
	return ""
}

func (m *Row) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Index)(nil), "dfuse.fluxdb.v1.Index")
	proto.RegisterMapType((map[string]uint32)(nil), "dfuse.fluxdb.v1.Index.PrimaryKeyToHeightEntry")
	proto.RegisterType((*Row)(nil), "dfuse.fluxdb.v1.Row")
}

func init() { proto.RegisterFile("dfuse/fluxdb/v1/fluxdb.proto", fileDescriptor_74afbad2e99b142c) }

var fileDescriptor_74afbad2e99b142c = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x80, 0xe5, 0xa6, 0xa5, 0xf4, 0xf8, 0x29, 0xb2, 0x40, 0x04, 0x04, 0x28, 0xea, 0x42, 0x16,
	0x1c, 0x95, 0x2e, 0x08, 0x36, 0x50, 0x25, 0x50, 0x17, 0x64, 0x31, 0xb1, 0x44, 0xf9, 0x71, 0x9b,
	0xa8, 0x6e, 0x1c, 0x52, 0xa7, 0xd4, 0x6f, 0xc2, 0xb3, 0xf1, 0x34, 0xc8, 0x76, 0x40, 0xa8, 0x88,
	0xed, 0xee, 0xfb, 0x7c, 0x67, 0x9f, 0x0f, 0xce, 0xd2, 0x69, 0xbd, 0x64, 0xc1, 0x94, 0xd7, 0xeb,
	0x34, 0x0e, 0x56, 0xc3, 0x26, 0x22, 0x65, 0x25, 0xa4, 0xc0, 0x7d, 0x63, 0x49, 0xc3, 0x56, 0xc3,
	0xc1, 0x27, 0x82, 0xce, 0x53, 0x91, 0xb2, 0x35, 0xbe, 0x84, 0xfe, 0xf2, 0xad, 0x66, 0x3c, 0xc9,
	0x58, 0x1a, 0x26, 0xa2, 0x2e, 0xa4, 0x8b, 0x3c, 0xe4, 0xb7, 0xe9, 0xfe, 0x0f, 0x7e, 0xd0, 0x14,
	0x47, 0x70, 0x54, 0x56, 0xf9, 0x22, 0xaa, 0x54, 0x38, 0x67, 0x2a, 0x94, 0x22, 0xcc, 0x58, 0x3e,
	0xcb, 0xa4, 0xdb, 0xf2, 0x1c, 0x7f, 0xe7, 0x9a, 0x90, 0x8d, 0x3b, 0x88, 0xe9, 0x4f, 0x9e, 0x6d,
	0xcd, 0x84, 0xa9, 0x17, 0xf1, 0x68, 0x0a, 0xc6, 0x85, 0xac, 0x14, 0xc5, 0xe5, 0x1f, 0x71, 0x3a,
	0x86, 0xe3, 0x7f, 0x8e, 0xe3, 0x03, 0x70, 0xe6, 0x4c, 0x99, 0xa7, 0xf5, 0xa8, 0x0e, 0xf1, 0x21,
	0x74, 0x56, 0x11, 0xaf, 0x99, 0xdb, 0xf2, 0x90, 0xbf, 0x47, 0x6d, 0x72, 0xdb, 0xba, 0x41, 0x83,
	0x0f, 0x04, 0x0e, 0x15, 0xef, 0xf8, 0x02, 0x20, 0x11, 0x9c, 0xb3, 0x44, 0xe6, 0xa2, 0x68, 0x4a,
	0x7f, 0x11, 0x7c, 0x0e, 0x20, 0xa3, 0x98, 0x33, 0xa9, 0x07, 0x32, 0x6d, 0x7a, 0xb4, 0x67, 0xc9,
	0x84, 0x29, 0xad, 0xed, 0x84, 0x46, 0x3b, 0x56, 0x5b, 0xa2, 0xf5, 0x09, 0x6c, 0xeb, 0x11, 0x8c,
	0x6c, 0x1b, 0xd9, 0xd5, 0xb9, 0x56, 0x2e, 0x74, 0xcb, 0x48, 0x71, 0x11, 0xa5, 0x6e, 0xc7, 0x43,
	0xfe, 0x2e, 0xfd, 0x4e, 0xef, 0x47, 0xaf, 0xc3, 0x59, 0x2e, 0xb3, 0x3a, 0x26, 0x89, 0x58, 0x04,
	0xe6, 0xc7, 0xae, 0x72, 0x11, 0x94, 0xf1, 0x4c, 0x04, 0x1b, 0x1b, 0xbc, 0x2b, 0x63, 0x1b, 0xc7,
	0x5b, 0x66, 0x89, 0xa3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xc9, 0x1f, 0x2f, 0xe4, 0x01,
	0x00, 0x00,
}
