// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sf/search/v1/search.proto

package pbsearchconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/streamingfast/pbgo/sf/search/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BackendName is the fully-qualified name of the Backend service.
	BackendName = "sf.search.v1.Backend"
	// RouterName is the fully-qualified name of the Router service.
	RouterName = "sf.search.v1.Router"
	// ForkResolverName is the fully-qualified name of the ForkResolver service.
	ForkResolverName = "sf.search.v1.ForkResolver"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BackendStreamMatchesProcedure is the fully-qualified name of the Backend's StreamMatches RPC.
	BackendStreamMatchesProcedure = "/sf.search.v1.Backend/StreamMatches"
	// RouterStreamMatchesProcedure is the fully-qualified name of the Router's StreamMatches RPC.
	RouterStreamMatchesProcedure = "/sf.search.v1.Router/StreamMatches"
	// ForkResolverStreamUndoMatchesProcedure is the fully-qualified name of the ForkResolver's
	// StreamUndoMatches RPC.
	ForkResolverStreamUndoMatchesProcedure = "/sf.search.v1.ForkResolver/StreamUndoMatches"
)

// BackendClient is a client for the sf.search.v1.Backend service.
type BackendClient interface {
	StreamMatches(context.Context, *connect.Request[v1.BackendRequest]) (*connect.ServerStreamForClient[v1.SearchMatch], error)
}

// NewBackendClient constructs a client for the sf.search.v1.Backend service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBackendClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BackendClient {
	baseURL = strings.TrimRight(baseURL, "/")
	backendMethods := v1.File_sf_search_v1_search_proto.Services().ByName("Backend").Methods()
	return &backendClient{
		streamMatches: connect.NewClient[v1.BackendRequest, v1.SearchMatch](
			httpClient,
			baseURL+BackendStreamMatchesProcedure,
			connect.WithSchema(backendMethods.ByName("StreamMatches")),
			connect.WithClientOptions(opts...),
		),
	}
}

// backendClient implements BackendClient.
type backendClient struct {
	streamMatches *connect.Client[v1.BackendRequest, v1.SearchMatch]
}

// StreamMatches calls sf.search.v1.Backend.StreamMatches.
func (c *backendClient) StreamMatches(ctx context.Context, req *connect.Request[v1.BackendRequest]) (*connect.ServerStreamForClient[v1.SearchMatch], error) {
	return c.streamMatches.CallServerStream(ctx, req)
}

// BackendHandler is an implementation of the sf.search.v1.Backend service.
type BackendHandler interface {
	StreamMatches(context.Context, *connect.Request[v1.BackendRequest], *connect.ServerStream[v1.SearchMatch]) error
}

// NewBackendHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBackendHandler(svc BackendHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	backendMethods := v1.File_sf_search_v1_search_proto.Services().ByName("Backend").Methods()
	backendStreamMatchesHandler := connect.NewServerStreamHandler(
		BackendStreamMatchesProcedure,
		svc.StreamMatches,
		connect.WithSchema(backendMethods.ByName("StreamMatches")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sf.search.v1.Backend/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BackendStreamMatchesProcedure:
			backendStreamMatchesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBackendHandler returns CodeUnimplemented from all methods.
type UnimplementedBackendHandler struct{}

func (UnimplementedBackendHandler) StreamMatches(context.Context, *connect.Request[v1.BackendRequest], *connect.ServerStream[v1.SearchMatch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sf.search.v1.Backend.StreamMatches is not implemented"))
}

// RouterClient is a client for the sf.search.v1.Router service.
type RouterClient interface {
	StreamMatches(context.Context, *connect.Request[v1.RouterRequest]) (*connect.ServerStreamForClient[v1.SearchMatch], error)
}

// NewRouterClient constructs a client for the sf.search.v1.Router service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRouterClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RouterClient {
	baseURL = strings.TrimRight(baseURL, "/")
	routerMethods := v1.File_sf_search_v1_search_proto.Services().ByName("Router").Methods()
	return &routerClient{
		streamMatches: connect.NewClient[v1.RouterRequest, v1.SearchMatch](
			httpClient,
			baseURL+RouterStreamMatchesProcedure,
			connect.WithSchema(routerMethods.ByName("StreamMatches")),
			connect.WithClientOptions(opts...),
		),
	}
}

// routerClient implements RouterClient.
type routerClient struct {
	streamMatches *connect.Client[v1.RouterRequest, v1.SearchMatch]
}

// StreamMatches calls sf.search.v1.Router.StreamMatches.
func (c *routerClient) StreamMatches(ctx context.Context, req *connect.Request[v1.RouterRequest]) (*connect.ServerStreamForClient[v1.SearchMatch], error) {
	return c.streamMatches.CallServerStream(ctx, req)
}

// RouterHandler is an implementation of the sf.search.v1.Router service.
type RouterHandler interface {
	StreamMatches(context.Context, *connect.Request[v1.RouterRequest], *connect.ServerStream[v1.SearchMatch]) error
}

// NewRouterHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRouterHandler(svc RouterHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	routerMethods := v1.File_sf_search_v1_search_proto.Services().ByName("Router").Methods()
	routerStreamMatchesHandler := connect.NewServerStreamHandler(
		RouterStreamMatchesProcedure,
		svc.StreamMatches,
		connect.WithSchema(routerMethods.ByName("StreamMatches")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sf.search.v1.Router/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RouterStreamMatchesProcedure:
			routerStreamMatchesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRouterHandler returns CodeUnimplemented from all methods.
type UnimplementedRouterHandler struct{}

func (UnimplementedRouterHandler) StreamMatches(context.Context, *connect.Request[v1.RouterRequest], *connect.ServerStream[v1.SearchMatch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sf.search.v1.Router.StreamMatches is not implemented"))
}

// ForkResolverClient is a client for the sf.search.v1.ForkResolver service.
type ForkResolverClient interface {
	StreamUndoMatches(context.Context, *connect.Request[v1.ForkResolveRequest]) (*connect.ServerStreamForClient[v1.SearchMatch], error)
}

// NewForkResolverClient constructs a client for the sf.search.v1.ForkResolver service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewForkResolverClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ForkResolverClient {
	baseURL = strings.TrimRight(baseURL, "/")
	forkResolverMethods := v1.File_sf_search_v1_search_proto.Services().ByName("ForkResolver").Methods()
	return &forkResolverClient{
		streamUndoMatches: connect.NewClient[v1.ForkResolveRequest, v1.SearchMatch](
			httpClient,
			baseURL+ForkResolverStreamUndoMatchesProcedure,
			connect.WithSchema(forkResolverMethods.ByName("StreamUndoMatches")),
			connect.WithClientOptions(opts...),
		),
	}
}

// forkResolverClient implements ForkResolverClient.
type forkResolverClient struct {
	streamUndoMatches *connect.Client[v1.ForkResolveRequest, v1.SearchMatch]
}

// StreamUndoMatches calls sf.search.v1.ForkResolver.StreamUndoMatches.
func (c *forkResolverClient) StreamUndoMatches(ctx context.Context, req *connect.Request[v1.ForkResolveRequest]) (*connect.ServerStreamForClient[v1.SearchMatch], error) {
	return c.streamUndoMatches.CallServerStream(ctx, req)
}

// ForkResolverHandler is an implementation of the sf.search.v1.ForkResolver service.
type ForkResolverHandler interface {
	StreamUndoMatches(context.Context, *connect.Request[v1.ForkResolveRequest], *connect.ServerStream[v1.SearchMatch]) error
}

// NewForkResolverHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewForkResolverHandler(svc ForkResolverHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	forkResolverMethods := v1.File_sf_search_v1_search_proto.Services().ByName("ForkResolver").Methods()
	forkResolverStreamUndoMatchesHandler := connect.NewServerStreamHandler(
		ForkResolverStreamUndoMatchesProcedure,
		svc.StreamUndoMatches,
		connect.WithSchema(forkResolverMethods.ByName("StreamUndoMatches")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sf.search.v1.ForkResolver/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ForkResolverStreamUndoMatchesProcedure:
			forkResolverStreamUndoMatchesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedForkResolverHandler returns CodeUnimplemented from all methods.
type UnimplementedForkResolverHandler struct{}

func (UnimplementedForkResolverHandler) StreamUndoMatches(context.Context, *connect.Request[v1.ForkResolveRequest], *connect.ServerStream[v1.SearchMatch]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sf.search.v1.ForkResolver.StreamUndoMatches is not implemented"))
}
