// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sf/merger/v1/merger.proto

package pbmergerconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/streamingfast/pbgo/sf/merger/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MergerName is the fully-qualified name of the Merger service.
	MergerName = "sf.merger.v1.Merger"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MergerPreMergedBlocksProcedure is the fully-qualified name of the Merger's PreMergedBlocks RPC.
	MergerPreMergedBlocksProcedure = "/sf.merger.v1.Merger/PreMergedBlocks"
)

// MergerClient is a client for the sf.merger.v1.Merger service.
type MergerClient interface {
	PreMergedBlocks(context.Context, *connect.Request[v1.Request]) (*connect.ServerStreamForClient[v1.Response], error)
}

// NewMergerClient constructs a client for the sf.merger.v1.Merger service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMergerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MergerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mergerMethods := v1.File_sf_merger_v1_merger_proto.Services().ByName("Merger").Methods()
	return &mergerClient{
		preMergedBlocks: connect.NewClient[v1.Request, v1.Response](
			httpClient,
			baseURL+MergerPreMergedBlocksProcedure,
			connect.WithSchema(mergerMethods.ByName("PreMergedBlocks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mergerClient implements MergerClient.
type mergerClient struct {
	preMergedBlocks *connect.Client[v1.Request, v1.Response]
}

// PreMergedBlocks calls sf.merger.v1.Merger.PreMergedBlocks.
func (c *mergerClient) PreMergedBlocks(ctx context.Context, req *connect.Request[v1.Request]) (*connect.ServerStreamForClient[v1.Response], error) {
	return c.preMergedBlocks.CallServerStream(ctx, req)
}

// MergerHandler is an implementation of the sf.merger.v1.Merger service.
type MergerHandler interface {
	PreMergedBlocks(context.Context, *connect.Request[v1.Request], *connect.ServerStream[v1.Response]) error
}

// NewMergerHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMergerHandler(svc MergerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mergerMethods := v1.File_sf_merger_v1_merger_proto.Services().ByName("Merger").Methods()
	mergerPreMergedBlocksHandler := connect.NewServerStreamHandler(
		MergerPreMergedBlocksProcedure,
		svc.PreMergedBlocks,
		connect.WithSchema(mergerMethods.ByName("PreMergedBlocks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sf.merger.v1.Merger/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MergerPreMergedBlocksProcedure:
			mergerPreMergedBlocksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMergerHandler returns CodeUnimplemented from all methods.
type UnimplementedMergerHandler struct{}

func (UnimplementedMergerHandler) PreMergedBlocks(context.Context, *connect.Request[v1.Request], *connect.ServerStream[v1.Response]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sf.merger.v1.Merger.PreMergedBlocks is not implemented"))
}
